### ISSUE TITLE
Incorrect binding for Observation.status in Atomic Imaging Observation and Atomic Pathology Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#100]
# Prerequisites

- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
In Atomic Imaging Observation and Atomic Pathology Observation the binding for Observation.status should be to [ObservationStatus Result Available](https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1).  

The value in Observation.status.binding.valueSet in the StructureDefinitions is "https://healthterminologies.gov.au/fhir/ValueSet/diagnostic-observation-status-1" which does not correspond to a known value set. 

The value should be "https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1".

## What I expected to happen
Observation.status to be bound to [ObservationStatus Result Available](https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1) as [required](http://hl7.org/fhir/terminologies.html#required).

**Comment by dtr-agency** [comment]
@RichardTON can you please confirm if this has been completed?

**Comment by dbojicic-agency** [comment]
Confirmed this change has been completed in [Atomic Imaging Observation](https://github.com/AuDigitalHealth/ci-fhir-r4/blob/master/resources/observation-imag-atomic-1.xml) and [Atomic Pathology Observation](https://github.com/AuDigitalHealth/ci-fhir-r4/blob/master/resources/observation-path-atomic-1.xml); Observation.status in both profiles is bound to [ObservationStatus Result Available](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/observationstatus-result-available-1) value set with the strength of 'required'.

**Comment by dbojicic-agency** [comment]
Closing this issue as completed.
