### ISSUE TITLE
Clinical Document Categorisation - develop terminology for DS, ES and SL sub-types

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-r4#102]
# The issue / feature
## Change description
Healthcare providers have difficulty in determining the content of a clinical document type (e.g. event summary) quickly and easily in their Clinical Information Systems and in the healthcare recipient’s My Health Record (MHR) that is relevant to the specific consult. It is time-consuming for healthcare providers and healthcare recipients to open each document on MHR to look for useful information, which could also lead to significant adoption barriers for healthcare providers and consumers to access to the MHR system. 

To that end, the Clinical Document Categorisation work activity seeks to introduce sub-type categorisation for the following 3 existing clinical document specifications:
- Discharge Summary (DS)
- Event Summary (ES)
- Specialist Letter (SL)

Terminology support needs to be developed, in conjunction with relevant stakeholders, to populate sub-type lists.,

## What it actually enables people to do
Clinicians can more easily find clinical documents of interest to them, relevant to the specific health concern of their patients.

## Mockups 
n/a

## How awesome would it be?
This would be a major step forwards in the usability of the MHR 

## Workarounds
n/a

**Comment by jaymeemurdoch** [comment]
The responsibility for defining the terminology for these subtypes has been passed to a different function within the Agency. This issue is now closed.
