### ISSUE TITLE
Code - Enduring Power of Attorney to support exchange of digital health in Australia

### ISSUE THREAD

**Issue by udaychandrupatla** [AuDigitalHealth/ci-fhir-r4#105]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
Identify an appropriate code or codes to represent the concept of Enduring Power of Attorney (EPOS).

Which is preferred when providing a transfer of care such as an Aged Care Transfer Summary - need to supply family / next of kin / enduring power of attorney information. 

There is an expectation in point-to-point the contact information may be provided but that in point-to-share only an individual has one or more persons fulfilling one or more of these.

## What it actually enables people to do
Provides information on authorised decision makers to healthcare providers, enabling deliver of care to patients.

## Mockups 
n/a

## How awesome would it be?
REUSE ME

## Workarounds
REUSE ME

## Additional context

1. [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) should support an EPOA contact
2. [AU Base Related Person](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-relatedperson.html) should support an EPOA relationship to the Patient

**Comment by dtr-agency** [comment]
### [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) should support an EPOA contact

Current value set [Contact Relationship Type](https://healthterminologies.gov.au/fhir/ValueSet/contact-relationship-type-3) does not yet include a value for Enduring Power of Attorney (EPOA).

The following request has been submitted to ADHA Terminology:
```
To support the Aged Care Transfer Summary it is requested that a SNOMED CT concept for Enduring Power of Attorney is added to this value set.

This value set is bound to the contact.relationshp element of [AU Base Patient|http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html]. 
```

Publication will be managed via [FHIR Terminology Requests](https://jira.aws.tooling/browse/FTR) [FTR-1493](https://jira.aws.tooling/browse/FTR-1493)

**Comment by dtr-agency** [comment]
### [AU Base Related Person](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-relatedperson.html) should support an EPOA relationship to the Patient

Current value set [Related Person Relationship Type](https://healthterminologies.gov.au/fhir/ValueSet/related-person-relationship-type-1) does not yet include a value for Enduring Power of Attorney (EPOA).

The following request has been submitted to ADHA Terminology:
```
To support the Aged Care Transfer Summary it is requested that a SNOMED CT concept for Enduring Power of Attorney is added to this value set.

This value set is bound to the relationship element of [AU Base Related Person](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-relatedperson.html).
```

Publication will be managed via [FHIR Terminology Requests](https://jira.aws.tooling/browse/FTR) [FTR-1493](https://jira.aws.tooling/browse/FTR-1488)

**Comment by dtr-agency** [comment]
Agency Terminology has advised the new concept 736801000168106|Enduring Power of Attorney| will be published in SNOMED CT AU to support EPOA. Publication of value sets and SNOMED CT AU release in progress, expected to be included in 30 June 2022 release.

**Comment by dtr-agency** [comment]
Publication confirmed.
