### ISSUE TITLE
StructureDefinition - Vital Signs panel to support exchange of digital health in Australia

### ISSUE THREAD

**Issue by udaychandrupatla** [AuDigitalHealth/ci-fhir-r4#106]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
In order to support the electronic _exchange_ of _useful_ vital sign information within _Australia TBD.

Vital signs reflect the body's physiological status. Measurement and interpretation of the the vital signs are significant components of assessment; it is done to obtain the base line about the patient condition, for diagnostic purposes, and for therapeutic purposes. Vital signs are assessed on admission, with every change in patient's health status, before of after the surgery or an invasive diagnostic procedure, etc. 

## What it actually enables people to do
TBD

## Mockups 
n/a

## How awesome would it be?
Vital sign data is pervasive throughout all aspects of healthcare, from child health assessments, to aged care transfer letters, and all points in between. Supporting the standard exchange of such content across all of these potential use cases would indeed be awesome.

## Workarounds
n/a

## Additional context
In order to support the provision of SNOMED codes for `Observation.code`, input from the Agency Terminology team was requested regarding specific SNOMED codes for each of the corresponding vital sign types. As at Aug 2021, the proposed codes are as follows:

| Vital sign type     | LOINC   | SNOMED                   |
|---------------------|---------|--------------------------|
| Blood pressure      | 85354-9 |`75367002\|Blood pressure\|`|
| Body height         | 8302-2  |`50373000\|Body height measure\|`|
| Body mass index     | 39156-5 |`60621009\|Body mass index\|`|
| Body temperature    | 8310-5  |`386725007\|Body temperature\|`|
| Body weight         | 29463-7 |`27113001\|Body weight\|`|
| Head circumference  | 9843-4  |**TBC** `363811000\|Head circumference measure\|`|
| Heart rate          | 8867-4  |`364075005\|Heart rate\|`|
| Oxygen saturation   | 2708-6  |`442476006\| Arterial oxygen saturation\|`|
| Respiratory rate    | 9279-1  |`86290005\| Respiratory rate\|`|

**Comment by robeastwood-agency** [comment]
A PR has just been merged into HL7AU master [hl7au/au-fhir-base/#717](https://github.com/hl7au/au-fhir-base/pull/717) that includes many improvements to the suite of 10 vital sign profiles. 

More refinements are expected in time to bring them to a state expected with higher levels of maturity.

**Comment by dtr-agency** [comment]
This work is now done. Refinements on the documentation of this issue may be added during closure.
