### ISSUE TITLE
Incorrect use of fixedCodeableConcept in various profiles

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-r4#11]
# Prerequisites

- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
Attempts to fix the value of system and code in CodeableConcept elements in various profiles are incorrectly using fixedCodeableConcept directly on the CodeableConcept element. The result of this prohibits CodeableConcept.text and CodeableConcept.coding.display (as well as other elements), which will inhibit the representation of realistic instances of data.
This is apparent in the following profiles:
- composition-es-1
- list-medseventchanges-1

## What I expected to happen
The fixed values are present as expected without prohibiting other useful elements.

## Workarounds
None

## Desktop (please complete the following information):
- N/A

## Additional context
One fix to this is to:
1. remove the fixedCodeableConcept directly on the affected CodeableConcept elements
2. add a fixed value on the respective CodeableConcept.coding.system and fixedCode on CodeableConcept.coding.code
3. manually make mandatory the following elements for each of the affected elements
- CodeableConcept.coding
- CodeableConcept.coding.system
- CodeableConcept.coding.code

However, this precludes alternate codings being allowed, which may not be appropriate in all circumstances.

**Comment by dtr-agency** [comment]
This issue was incorrectly migrated to this repository from ci-fhir-stu3. No profiles use fixedCodeableConcept in this repository - this is bug is invalid for ci-fhir-r4.
