### ISSUE TITLE
My Health Record Other Diagnostic Report: Organization requester

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#110]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
The DaignosticReport invariant "_inv-dh-dir-03: The requester of the diagnostic investigation order shall be a PractitionerRole_" mandates the requester is a PractitionerRole; however ServiceRequest.basedOn allows for PractitionerRole and Organization and in some scenario's it is appropriate for an organization to  be the requester of an investigation.
Further investigation is required to determine if the invariant "inv-dh-dir-03" should be removed.

## What it actually enables people to do
If an organisation can order a request for an other diagnostic report then the invariant in the DiagnosticReport needs to be deleted to remove the restriction of only a PractitionerRole being able to make such an order.

## Mockups 
n/a

## How awesome would it be?
It would be great to have clarity on whether an organisation can request an other diagnostic report and if so the constraint limiting the request to a PractitionerRole can be removed.

## Workarounds
There is limited work arounds available i.e if an organisation can order an other diagnostic report then there is little that can be done to indicate this with the current invariant.

## Additional context
n/a

**Comment by dtr-agency** [comment]
Discussion with BA, Product Owner, CI Team. An order may be made by providers, organisations, patients and related persons e.g. mother).

The invariant should not be present in the My Health Record Other Diagnostic Report profile (or equivalent profile).

**Comment by dtr-agency** [comment]
Fixed in commit a02521daa275f04435d7582215de834744c73f79
