### ISSUE TITLE
Support exchange of CALD (Cultural and Linguistic Diversity) minimum data set

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#13]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
Provision of support for minimum CALD (Cultural and Linguistic Diversity) data set in electronic health information exchange in Agency FHIR and CDA specifications:
- Country of birth 
- Preferred language 
-  Need for interpreter 
- Year of arrival in Australia 
- Ethnicity

## What it actually enables people to do
Enablers for delivery of culturally and linguistically appropriate services for health care consumers and improved understanding of cultural and linguistic diversity within the population.

## How awesome would it be?
Awareness of a consumer's cultural and linguistic requirements enables providers to provide access to culturally appropriate resources, in consumers’ first language, on health issues and to improve inclusion of consumer needs in care planning. 
Improved understanding of cultural and linguistic diversity within the population supports planning and delivery of services for a diverse potential target population.

## Workarounds
N/A

## Additional context
**Country of birth** is already supported in Agency FHIR and CDA specifications:
| Specification | Description of support | 
| ------------- | ------------- | 
| Legacy Agency CDA specifications | SCS Data component _SUBJECT OF CARE > PARTICIPANT > PERSON > DEMOGRAPHIC DATA > Country of Birth_ with CDA schema element of `ClinicalDocument/recordTarget/patientRole/patient/birthplace/place/addr/country`|
| FHIR-driven CDA specifications | Logical element of _Patient > birthPlace_ with associated CDA schema element of `ClinicalDocument/recordTarget/patientRole/patient/birthplace/place/addr/country` |
|Agency FHIR implementation guides | `Patient.extension:birthPlace.valueAddress.country` |

**Preferred language** is already supported in Agency FHIR and recent FHIR-driven CDA specifications:
| Specification | Description of support | 
| ------------- | ------------- | 
| Legacy Agency CDA specifications | Not explicitly modelled; may be included as a local extension using the FHIR-driven CDA specification mappings |
| FHIR-driven CDA specifications | Logical elements _Patient > communication > language_ & _Patient > communication > preferred_ with associated CDA schema element of `ClinicalDocument/recordTarget/patientRole/patient/languageCommunication` with `//languageCommunication/preferenceInd/value="true"` and `//languageCommunication/languageCode/code`|
|Agency FHIR implementation guides | `Patient.communication.language` and `Patient.comunication.preferred` as `"true"` |

**Need for interpreter** not yet supported in Agency specifications but core extensions on Patient resource are available, see http://hl7.org/fhir/R4/patient-profiles.html. 

### Reference materials
ABS reference materials relating to CALD:
- [1289.0 - Standards for Statistics on Cultural and Language Diversity, 1999](https://www.abs.gov.au/AUSSTATS/abs@.nsf/Latestproducts/1289.0Main%20Features11999?opendocument&tabname=Summary&prodno=1289.0&issue=1999&num=&view=) which has been superseded by the following:
- [1200.0.55.004 - Country of Birth Standard, 2016](https://www.abs.gov.au/ausstats/abs@.nsf/mf/1200.0.55.004)
- [1200.0.55.005 - Language Standards, 2016](https://www.abs.gov.au/ausstats/abs@.nsf/mf/1200.0.55.005)
- [1200.0.55.009 - Ancestry Standard, 2014, Version 2.1](https://www.abs.gov.au/ausstats/abs@.nsf/mf/1200.0.55.009)
- [1200.0.55.010 - Australian Citizenship Standard, 2014, Version 1.2](https://www.abs.gov.au/ausstats/abs@.nsf/mf/1200.0.55.010)
- [1200.0.55.008 - Indigenous Status Standard , 2014, Version 1.5](https://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1200.0.55.008Main+Features12014,%20Version%201.5?OpenDocument)
- [1200.0.55.003 - Religious Affiliation Standard, 2016](https://www.abs.gov.au/ausstats/abs@.nsf/mf/1200.0.55.003)
- [1266.0 - Australian Standard Classification of Religious Groups, 2016](https://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1266.0Main+Features12016?OpenDocument)
- [1200.0.55.007 - Year of Arrival Standard, 2014, Version 1.5](https://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1200.0.55.007Glossary12014,%20Version%201.5?OpenDocument)

AIHW METeOR relating to CALD:
- [Cultural and language diversity cluster](https://meteor.aihw.gov.au/content/index.phtml/itemId/491352) 
- [Person—religious affiliation](https://meteor.aihw.gov.au/content/index.phtml/itemId/269421), [Person—religious affiliation, code (ASCRG 2011) N[NNN]](https://meteor.aihw.gov.au/content/index.phtml/itemId/493242), [Religious group code (ASCRG 2011) N[NNN]](https://meteor.aihw.gov.au/content/index.phtml/itemId/493240)
- [Person—year of first arrival in Australia](https://meteor.aihw.gov.au/content/index.phtml/itemId/269447) , [Person—year of first arrival in Australia, date YYYY](https://meteor.aihw.gov.au/content/index.phtml/itemId/269929), [Year of first arrival in Australia](https://meteor.aihw.gov.au/content/index.phtml/itemId/269050)
- [Person—interpreter service required](https://meteor.aihw.gov.au/content/index.phtml/itemId/639621), [Interpreter service required indicator](https://meteor.aihw.gov.au/content/index.phtml/itemId/639619), [Person—interpreter service required indicator, yes/no/not stated/inadequately described code N](https://meteor.aihw.gov.au/content/index.phtml/itemId/639616), [Person—type of interpreter service required, spoken language/non-spoken communication code N](https://meteor.aihw.gov.au/content/index.phtml/itemId/623483)
- [Person—preferred language](https://meteor.aihw.gov.au/content/index.phtml/itemId/269744), [Person—preferred language, code (ASCL 2016) N[NNN]](https://meteor.aihw.gov.au/content/index.phtml/itemId/659407), [Allied health service event—preferred language](https://meteor.aihw.gov.au/content/index.phtml/itemId/705846), [Allied health service event—preferred language, code (ASCL 2016) N[NNN]](https://meteor.aihw.gov.au/content/index.phtml/itemId/705848), [Preferred language](https://meteor.aihw.gov.au/content/index.phtml/itemId/269244)
- [Person—Indigenous status](https://meteor.aihw.gov.au/content/index.phtml/itemId/615458), [Indigenous status](https://meteor.aihw.gov.au/content/index.phtml/itemId/269161), [Person—Indigenous status, code N](https://meteor.aihw.gov.au/content/index.phtml/itemId/723676), [Person—Indigenous status, code N](https://meteor.aihw.gov.au/content/index.phtml/itemId/602543)

**Comment by dtr-agency** [comment]
Suggest **Year of arrival in Australia** be an HL7 AU extension on Patient in HL7 AU Base. The definition of this element in ABS and AIHW is fairly well understood as:

> the year a person (born outside of Australia) first arrived in Australia, from another country, with the intention of living in Australia for one year or more.

In the ABS standard year is collected and stored as four-digit calendar years (e.g. a response of '1985' is coded as '1985' in the classification). In AIHW this is a date of YYYY.

Questions: 
1. is there a need or would this be useful as a core extension for "Year of arrival"?
2. Suggest the data type is a date constrained to years (obviously not a quantity :))?

**Comment by robeastwood-agency** [comment]
Given that this content would be valuable at a broader national scale, it is planned to be raised at the [next HL7 Patient Administration Working Group (PAWG) meeting](https://confluence.hl7australia.com/display/PA/2020-02-26+Minutes), scheduled for 26 Feb 2020. This may result in aspects of the minimum data set being implemented in the [HL7 AU Base Implementation Guide](http://build.fhir.org/ig/hl7au/au-fhir-base/index.html).

**Comment by robeastwood-agency** [comment]
Discussed at the 26 Feb PAWG with agreement (see [minutes](https://confluence.hl7australia.com/display/PA/2020-02-26+Minutes)) to proceed with 2 additions to the AU Base Patient profile:
1. add the core extension [patient-interpreterRequired](http://hl7.org/fhir/extension-patient-interpreterrequired.html) (with context of Patient and 0..1); see GitHub ticket #[356](https://github.com/hl7au/au-fhir-base/issues/356)
1. Creation of new extension in the HL7 AU Base IG to cater for the year of arrival to Australia.

**Comment by robeastwood-agency** [comment]
Created internal Agency task ticket to progress the addition of interpreterRequired extension: 
- HL7 AU Base Patient - add extension for interpreterRequired - [JIRA: CIFMM-3315](https://jira.digitalhealth.gov.au/browse/CIFMM-3315)

**Comment by dtr-agency** [comment]
Created internal Agency task tickest to create Patient profiles that include support for CALD elements: [Create R4 Patient profiles (My Health Record)](https://jira.digitalhealth.gov.au/browse/CIFMM-3257) & [Create R4 Patient profiles (Patient with Mandatory Identifier)](https://jira.digitalhealth.gov.au/browse/CIFMM-3317)

**Comment by robeastwood-agency** [comment]
**Re year of arrival** - the CI team will workshop a proposed design for the extension to the HL7 AU Base patient profile, to bring to a forthcoming PAWG, for ratification.

**Comment by robeastwood-agency** [comment]
**Re year of arrival** - the CI team has work-shopped the design of an extension and is now a PR on HL7 AU (https://github.com/hl7au/au-fhir-base/pull/404) - for discussion at PAWG

**Comment by robeastwood-agency** [comment]
The AU Base Patient profile now includes the extension [Date of Arrival](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-date-of-arrival.html).

The newly created Patient with Mandatory Identifier profile has this element as must support = true.

**Comment by dtr-agency** [comment]
My Health Record Patient profile has included the additional elements with must support via https://github.com/AuDigitalHealth/ci-fhir-r4/commit/8e0b5a424ea2dd3bc120d0210c12825ff7370eee#diff-55b558c7ef820e6e00e5993b9e55d93b

**Comment by dtr-agency** [comment]
CDA mappings from this work will be progressed in a different internal story.

@robeastwood-agency what is left to do?

HL7 AU Base pull requests and issues are closed - extensions are included in HL7 AU Base Patient profile with examples and some usage notes
Agency pull requests and issues are closed - must support in Agency Patient profiles with at least one example and some implementation guidance

**Comment by robeastwood-agency** [comment]
The implementable aspects of the CALD data set have now been implemented in HL7 AU, with support in derived Agency profiles. The 2 remaining aspects of this work will be managed as separate tickets:
- Ethnicity - awaiting necessary agreements in the business before anything can be progressed
- CDA mappings - as described above by @dtr-agency

**Comment by dtr-agency** [comment]
Need for interpreter CDA extension is now published in the [Australian Digital Health Agency CDA Schema Extension 3.0 - CDA Schema v20201203](https://developer.digitalhealth.gov.au/specifications/ehealth-reference-platform/ep-3546-2021/dh-3491-2021)
