### ISSUE TITLE
Categorisation of Health Program Participation Observation

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#137]
DESIGN QUERY: 
Observation.category - current discussion indicates that ‘therapy’ or ‘social history’ are closest fit from existing [Observation Category Codes](http://build.fhir.org/valueset-observation-category.html) but these are not ideal. Proposal is to extend the HL7 Int set of concepts with a localised concept for health programs including treatment programs and prevention programs. Proposed concept is ‘program’ with definition ‘Observations that describe an individual’s participation in one or more health programs such as treatment or prevention or public health (e.g. disease screening or substance use therapy)’.

_Originally posted by @dtr-agency in https://github.com/AuDigitalHealth/ci-fhir-r4/issues/134#issuecomment-1058662760_

**Comment by dtr-agency** [comment]
Proposal is visible in [Health Program Participation Observation (for transition to HL7 AU)](https://build.fhir.org/ig/AuDigitalHealth/ci-fhir-r4/StructureDefinition-dh-observation-programparticipation-1.html)

**Comment by dtr-agency** [comment]
##New concept proposal 

Reason | New concept
-- | --
Terminology | Observation Category Codes - AU Extendedhttp://terminology.hl7.org.au/CodeSystem/observation-category
Suggested Concept | program
Suggested Display of Concept | Program
Detailed Description | Observations that describe an individual’s participation in one or more health programs such as treatment or prevention or public health (e.g. disease screening or substance use therapy).
Business Reason for Request | To support the exchange of health program participation information in Australia as part of the the current work plan initiative: NCSR integration with MHR system.

**Comment by dtr-agency** [comment]
Post normalisation design review in https://github.com/AuDigitalHealth/ci-fhir-r4/issues/134 approved this design to progress to draft build and submission of PR for adoption into AU Base subject to WG Approval and entry into HL7 AU Governance.

**Comment by dtr-agency** [comment]
## Value set design

Reason | New value set
-- | --
Suggested Name | ObservationCategoryCodesAUExtended
Suggested Title | Observation Category Codes - AU Extended
Suggested URI | http://terminology.hl7.org.au/ValueSet/observation-category
Suggested Description | Observation Category Codes extended for use in an Australian context.
Terminologies included | http://terminology.hl7.org/CodeSystem/observation-categoryhttp://terminology.hl7.org.au/CodeSystem/observation-category
Compose requirements | Include all codes defined in http://terminology.hl7.org.au/CodeSystem/observation-categoryImport all the codes that are contained in http://hl7.org/fhir/ValueSet/observation-category
Business Reason for Request | To support the exchange of health program participation information in Australia as part of the the current work plan initiative: NCSR integration with MHR system.Additionally, it is expected that an AU localisation will be required to support the expansion of definitions in HL7 AU materials.


</body>
</html>

**Comment by dtr-agency** [comment]
@dbojicic-agency, please review the proposed value set, code system, and concept.

**Comment by dbojicic-agency** [comment]
In review with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
**Review comments - concept**
Agree with the proposed concept.

**Review comments - code system**
Minor deviation in the proposed definition from the [Conventions for extending a core (or external) terminology in Australia](https://github.com/hl7au/au-fhir-base/wiki#conventions-for-extending-a-core-or-external-terminology-in-australia), 
suggest change to 'Extended concept codes for observation category codes for use in an Australian context.'

**Review comments - value set**
Minor deviation in the proposed URL from the [Conventions for extending a core (or external) terminology in Australia](https://github.com/hl7au/au-fhir-base/wiki#conventions-for-extending-a-core-or-external-terminology-in-australia), 
suggest change to 'http://terminology.hl7.org.au/ValueSet/observation-category-extended'.

**Comment by dbojicic-agency** [comment]
@dtr-agency, completed review, please see comments above.

**Comment by dtr-agency** [comment]
Content proposal is complete. This material will be developed when develop as part of submitting a draft national health program participation model to [AU FHIR Base](https://github.com/hl7au/au-fhir-base) for adoption into [Australian Base Implementation Guide (AU Base 2)](http://build.fhir.org/ig/hl7au/au-fhir-base/index.html) subject to WG Approval and entry into HL7 AU Governance via [Definition of health program participation observation (summary information) #134](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/134)

**Comment by dtr-agency** [comment]
Internal PR .../CIL/repos/au-fhir-base-r4/pull-requests/237 in review with @dbojicic-agency.
