### ISSUE TITLE
Organ or Tissue for Donation Terminology - Support transition between the CDA or RIM and FHIR formats

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#146]
Issue in supporting transition between the CDA or RIM format and the FHIR format (both STU3 and R4) of an [Australian Organ Donor Register form](https://www.servicesaustralia.gov.au/nh007df). 

The terminology that represents organ or tissue for donation doesn't have a defined transition from the NCTIS terminology supported in the original CDA (RIM) format and the SNOMED CT terminology supported in the FHIR format.

The CDA format supports the legacy value set [NCTIS Organ Donation Consent Component Indicators](https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-consent-tbd-1) that uses concepts from [NCTIS Data Components](https://healthterminologies.gov.au/fhir/CodeSystem/nctis-data-components-1) code system.

The FHIR format supports the value set [Organ Donation Body Site](https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-body-site-1) that uses concepts from SNOMED CT.

Concept maps are required to define to define that transition but are not yet available.

_Originally posted by @dtr-agency in https://github.com/AuDigitalHealth/ci-fhir-r4/issues/141#issuecomment-1092258367_

**Comment by dtr-agency** [comment]
Publication of the CDA (RIM) legacy value set [NCTIS Organ Donation Consent Provision Type](https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-consent-provision-type-1) is being managed by [FHIR Terminology Requests](https://jira.aws.tooling/browse/FTR) [FTR-103](https://jira.aws.tooling/browse/FTR-103).

**Comment by dtr-agency** [comment]
## Early proposal for concept maps

### CDA (RIM) to FHIR

Element | Description
-- | --
Suggested Title of Value Set | NCTIS Organ Donation Consent Provision Type to Organ Donation Body Site
Suggested URI | https://healthterminologies.gov.au/fhir/ConceptMap/
Suggested Description | The NCTIS Organ Donation Consent Provision Type to Organ Donation Body Site concept map defines relationships from the concepts in the NCTIS Organ Donation Consent Provision Type value set to the concepts in the Organ Donation Body Site value set. 
Source ValueSet | https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-consent-provision-type-1
Target ValueSet | https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-body-site-1

Source Concept | Equivalence | Target Concept
-- | -- | -- 
103.16661 | equivalent | 272673000
103.16662 | equivalent | 81745001
103.16669 | equivalent | 39937001
103.16663 | equivalent | 80891009
103.16664 | equivalent | 17401000
103.16665 | equivalent | 64033007
103.16666 | equivalent | 10200004
103.16667 | equivalent | 39607008
103.16668 | equivalent | 15776009

### FHIR to CDA (RIM)

Element | Description
-- | --
Suggested Title of Value Set | Organ Donation Body Site to NCTIS Organ Donation Consent Provision Type
Suggested URI | https://healthterminologies.gov.au/fhir/ConceptMap/
Suggested Description | The Organ Donation Body Site to NCTIS Organ Donation Consent Provision Type concept map defines relationships from the concepts in the Organ Donation Body Site value set to the concepts in the NCTIS Organ Donation Consent Provision Type value set.
Source ValueSet | https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-body-site-1
Target ValueSet | https://healthterminologies.gov.au/fhir/ValueSet/organ-donation-consent-provision-type-1


Source Concept | Equivalence | Target Concept
-- | -- | -- 
272673000 | equivalent | 103.16661
81745001 | equivalent | 103.16662
39937001 | equivalent | 103.16669
80891009 | equivalent | 103.16663
17401000 | equivalent | 103.16664
64033007 | equivalent | 103.16665
10200004 | equivalent | 103.16666
39607008 | equivalent | 103.16667
15776009 | equivalent | 103.16668

**Comment by dbojicic-agency** [comment]
Completed initial review of the two concept maps with no issues related to the proposed content found. 
Noting that proposed URIs are incomplete which is probably expected at this stage given the pending ValueSet FTRs.

**Comment by adnil01** [comment]
CDA (RIM) to FHIR concept map reviewed with no issues.
FHIR to CDA (RIM) concept map reviewed with no issues.

The program refers to organ and tissue donation - Suggest the inclusion of _tissue_ in the Title and the descriptions etc ie:

_NCTIS Organ and Tissue Donation Consent Provision Type to Organ and Tissue Donation Body Site_

_Organ and Tissue Donation Body Site to NCTIS Organ and Tissue Donation Consent Provision Type_

**Comment by adnil01** [comment]
CDA (RIM) to FHIR concept map reviewed with no issues.
FHIR to CDA (RIM) concept map reviewed with no issues.

The program refers to organ and tissue donation - Suggest the inclusion of tissue in the Title and the descriptions etc ie:

NCTIS Organ and Tissue Donation Consent Provision Type to Organ and Tissue Donation Body Site

Organ and Tissue Donation Body Site to NCTIS Organ and Tissue Donation Consent Provision Type

**Comment by dtr-agency** [comment]
@lindaa-agency, the title and descriptions of the Concept Maps use the titles of the source and target value sets. If a used value set title changes, the concept map will update as a result.

**Comment by dtr-agency** [comment]
Above request provided to ADHA Terminology, request managed by [FHIR Terminology Requests](https://jira.aws.tooling/browse/FTR) [FTR-1533](https://jira.aws.tooling/browse/FTR-1533) & [FTR-1528](https://jira.aws.tooling/browse/FTR-1528).

**Comment by dtr-agency** [comment]
NCTIS value set title changed as per recommendation from terminology analyst - design above edited.

**Comment by dtr-agency** [comment]
ValueSet reviewed and approved for publication. Publication scheduled for May 2022 release.

**Comment by dtr-agency** [comment]
Published in NCTS.
