### ISSUE TITLE
Use FHIR version independent canonical URLs for Agency profiles

### ISSUE THREAD

**Issue by RichardTON** [AuDigitalHealth/ci-fhir-r4#17]
# Prerequisites
- [X ] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X ] I have written a descriptive issue title

# The issue / feature
## Change description
Use FHIR version independent canonical URLs for Agency profiles, where possible.

## What it actually enables people to do
Allows systems to use FHIR resources (and profiles) that do not change between FHIR versions without changes changes to the system.

## How awesome would it be?
 As FHIR matures this will be a considerable saving of work for designers and implementers. They will not have to make changes when the profile has not changed but the FHIR version has.

## Workarounds
N/A

## Additional context
During development of FHIR STU3 profiles, CI used canonical URLs that are FHIR version specific. See [FHIR profile canonical url conventions](https://confluence.digitalhealth.gov.au/display/CIN/FHIR+profile+canonical+url+conventions).

**Comment by RichardTON** [comment]
MHR Patient is a candidate as its foundations look stable.
Patient became normative in R4.
Are its other foundations, extensions, bindings, AU Base patient stable in all important respects?
Identify criteria for deciding and apply them.

**Comment by dtr-agency** [comment]
Existing examples that include a meta.profile assertion that is now out of date... need to be updated; progressing via internal ticket [CIFMM-3534](https://jira.digitalhealth.gov.au/browse/CIFMM-3534).
