### ISSUE TITLE
Simple Pathology Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#20]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
Development of a profile to represent key elements of clinical relevance (such as pathology test name and test date time) to accompany a rich text representation of a pathology report as issued by the diagnostic service provider for the electronic exchange of pathology reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The main context of this profile is to support the existing requirements for My Health Record Pathology Report content in a FHIR format and drive CDA-based FHIR.

The existing CDA implementation including requirements can be found here: [eHealth Pathology Report v1.2.2](https://developer.digitalhealth.gov.au/specifications/clinical-documents/ep-2558-2017)
## What it actually enables people to do
This profile supports the identification of tests performed for a patient enabling an individual to determine if the Pathology Report is of interest but does not directly support reporting of the actual results of pathology tests (see Atomic Pathology Observation for atomic reporting).
The observation may represent the result of a simple test such as haematocrit or it may group the set of results produced by a multi-test study or panel such as a full blood count, or urine specimen study. In the latter cases, the observation carries the code of the study / panel and references the individual tests that make up the study / panel as ‘has-member’ child observations.
## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Workarounds
No good ones, potentially use of [AU Diagnostic Observation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnostic-observation.html) could offer some value with terminology but meaningful use is not supported without further derivation and guidance.

## Additional context
[eHealth Pathology Report v1.2.2](https://developer.digitalhealth.gov.au/specifications/clinical-documents/ep-2558-2017)

[View pathology and diagnostic imaging reports](https://www.myhealthrecord.gov.au/for-you-your-family/howtos/view-pathology-and-diagnostic-imaging-reports)

[Pathology reports in My Health Record](https://www.myhealthrecord.gov.au/for-healthcare-professionals/howtos/pathology-reports)

**Comment by davidmckillop** [comment]
Phase 1 shell profile Simple Pathology Observation profile been completed.
The shell profile has the basic structure but is missing constraints and terminology bindings.
Profile page in Diagnostics Report FHIR IG includes a list of known issues for the profile.

**Comment by dtr-agency** [comment]
The ValueSet design in #59 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
- No 'work in progress' issues remain:
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1"
   - code is bound as preferred uri = "https://healthterminologies.gov.au/fhir/ValueSet/pathology-procedure-1"
   - subject (Reference type too open)
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated - affects profiles My Health Record Patient, PractitionerRole with Mandatory Identifier
- intro.md has good introductory material (context, purpose) and implementation guidance, there are no TBDs
- Known issues is complete, correct, up-to-date and written for an external audience

**Comment by dtr-agency** [comment]
Walked through with product owner (@davidmckillop); slight intro.md changes and known issue change made.

**Comment by dtr-agency** [comment]
Sent for review with @vikasmittal-dh

**Comment by dtr-agency** [comment]
Reviewer noted the intro page says - status will be ‘preliminary’, ‘final’, or ‘amended’ - while the profile shows "registered | preliminary | final | amended +".

Response: the intro contains implementation guidance - further suggestions that aren't in the StructureDefinition. So it is totally ok and intended that the StructureDefinition has more codes allowed than the guidance - there would be no reason to say it in guidance if that was the case.

However since the highlighted text is the short and it actually includes a code that we have removed I think its a good idea to edit that short to remove the code we took out or its misleading. I will do that now.

Product owner agreed. 
Change made and in review with @vikasmittal-dh for confirmation.

**Comment by dtr-agency** [comment]
Passed internal review; rebuilt Diagnostic Report output and on master to include the shell profile with placeholder introductory content. See https://github.com/AuDigitalHealth/ci-fhir-r4/commit/723d66e581d8e0d34d8d6100d13853bf6b5c1721
