### ISSUE TITLE
My Health Record Pathology Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#23]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
The purpose of this profile is to define a short form representation providing a rich text representation of the report as issued by the diagnostic service provider with supporting key elements of clinical relevance for the electronic exchange of pathology reports between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by SatyaYelisetti** [comment]
Shell profile of My Health Record Pathology Report has been created and is currently under review.

**Comment by SatyaYelisetti** [comment]
Shell profile of My Health Record Pathology Report has been created and can be found at the above commit.

**Comment by dtr-agency** [comment]
The ValueSet design in #61 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/pathology-diagnostic-service-category-1.

**Comment by dtr-agency** [comment]
The ValueSet design in #58 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1.

**Comment by davidmckillop** [comment]
This issue is now closed. Remaining known issues are documented in the profile's known issue table.
