### ISSUE TITLE
Collected specimen profile

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#24]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
The purpose of this profile is to represent key elements of clinical relevance of a collected specimen to accompany a diagnostic observation issued by the diagnostic service provider for the electronic exchange of diagnostic test observations between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by robeastwood-agency** [comment]
Commenced work on the profile.

**Comment by robeastwood-agency** [comment]
An initial profile 'shell' is now available in the Diagnostic Report IG. Refer to commit https://github.com/AuDigitalHealth/ci-fhir-r4/commit/87bf2df3a39ac67391bb5635beaccd56858382a7

The next stage of development (not scheduled as yet) will include:
- enforcing Reference on subject and collection.collector
- enforce terminology on type, collection.method, collection.bodySite

**Comment by dbojicic-agency** [comment]
Made further changes in the profile to:
- constrain the Reference type on subject by invariant to at least have a reference or an identifier with a system and a value
- constrain the Reference type on collection.collector by invariant to at least have a reference or an identifier with a system and a value
- proliferated canonical URL changes (remove 4.0); this affects Patient with Mandatory Identifier, My Health Record Patient and PractitionerRole with Mandatory Identifier)
- added introductory and implementation guidance content

The profile still has known issues:
|Reference|Description|
|-----------|------------|
|self collection (not currently support)|It is not understood how self collection can be supported in this profile. There is no element or core extension available for Specimen that identifies a patient or related person as a collector. <br/>Self collection of bloods or other material including sent by mail kits cancer screening are to be a supported usage scenario.|
|Support for screening programs initiated requests|Not yet clear how requests that are initiated by a national program, e.g. [National Bowel Cancer Screening Program](http://www.cancerscreening.gov.au/internet/screening/publishing.nsf/Content/bowel-screening-1), are supported with this model - work in progress.|
|type (coding terminology enforcement)|It is intended that the slice from [HL7 AU Base Specimen](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-specimen.html) coding:snomedSpecimenType should be enforced if any coding is provided. In other words, either text or a code from this value set is required. This is a work in progress.|
|collection.method (coding terminology enforcement)|It is intended that the slice from [HL7 AU Base Specimen](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-specimen.html) coding:snomedSpecimenCollectionProcedure should be enforced if any coding is provided. In other words, either text or a code from this value set is required. This is a work in progress.|
|collection.bodySite (coding terminology enforcement)|It is intended that the slice from [HL7 AU Base Specimen ](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-specimen.html) coding:snomedBodySite should be enforced if any coding is provided. In other words, either text or a code from this value set is required. This is a work in progress.|

**Comment by dtr-agency** [comment]
@dusica and @davidmckillop is there a reason we did not enforce the terminology in this? 

I can't spot the GitHub issues for enforcing terminology slicing in Specimen in our GitHub - we need those to finish this feature off.

**Comment by davidmckillop** [comment]
@dtr-agency - the slices for terminology in [HL7 AU Base Specimen](https://build.fhir.org/ig/hl7au/au-fhir-base//StructureDefinition-au-specimen.html) were not functional and hence were changed in [#425](https://github.com/hl7au/au-fhir-base/pull/425) where the slices were removed and the bindings changed to preferred.

**Comment by dtr-agency** [comment]
@davidmckillop - what action has been taken instead?

**Comment by davidmckillop** [comment]
@dtr-agency - an update to the profile has been completed.
