### ISSUE TITLE
Pathology category terminology for DiagnosticReport

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#25]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
The example value set is too broad for pathology reporting - we need a value set that is a constrained value set from that example set [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) that is restricted to the pathology appropriate codes. This value set would become required.

This change applies to:
* DiagnosticReport (My Health Record Pathology Report)
* DiagnosticReport (Atomic Pathology Report)

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dtr-agency** [comment]
This was completed as part of phase 2.
https://github.com/AuDigitalHealth/ci-fhir-r4/issues/23
https://github.com/AuDigitalHealth/ci-fhir-r4/issues/21
