### ISSUE TITLE
My Health Record Pathology Report - effective[x]

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#26]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
The My Health Record system expects only a dateTime; period is a relevant type for some pathology tests e.g. a 24 hours urine collection tests will have collection times of start at 08:00 6/4/2020 to finish at 08:00 7/4/2020. The constraining of types should be reconfirmed.

Will need to confirm with system providers and the RCPA the intent and use of effectiveTime.period.

## What it actually enables people to do
Clarification would enable clearer expectations on the presence of a report with an effectiveTime (period) in the MHR.

## How awesome would it be?
Clarification of the use of a time duration (period) for an effective time would enable the presentation of all types of pathology reports.

## Workarounds
If a period is not acceptable as an effectiveTime in a MHR, then either:
1)  All reports with a period are rejected from the MHR;  OR
2) the first time in the time duration (period) is used as the effectiveTime (instance).

## Additional context
n/a

**Comment by dtr-agency** [comment]
Date time and period are accepted in ADHA core profiles in line with international standards and other material including HL7 AU materials, International Patient Summary FHIR IG, US Core FHIR IG.
