### ISSUE TITLE
Atomic Pathology Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#30]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to represent an atomic representation of a pathology test observation issued by the diagnostic service provider for the electronic exchange of pathology test observations between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dbojicic-agency** [comment]
In progress via internal ticket CIFMM-3399.

**Comment by dbojicic-agency** [comment]
An initial profile 'shell' is now available in the Diagnostic Report IG. Refer to commit

Phase 2 of the development will include:
- Reference type enforcement for subject, performer
- shall have value or dataAbsentReason or hasMember

**Comment by dtr-agency** [comment]
The ValueSet design in #59 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1.

**Comment by dtr-agency** [comment]
Completed by @rodney-collins-agency via dca7e0a72d0aa9c364d5a0e758f63a9cd46da856.

Phase 2 included:
 - No 'work in progress' issues remain:
 ** status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/diagnostic-observation-status-1"
 ** code is bound as preferred uri = "https://healthterminologies.gov.au/fhir/ValueSet/pathology-procedure-1"
 ** subject (Reference type too open) - {color:#ff8b00}low value item{color} 
 ** performer (Reference type too open) - {color:#ffab00}low value item{color} 
 ** to enforce that there has to be either content in hasMember or dataAbsentReason, but not both -{color:#ffab00} low value item {color}
 # performer is restricted to at most one PractionerRole and at most one Organization and possibly one of each.  - {color:#ffab00}low value item {color}
 Note: This might be done as slices or an invariant - discuss with product owner:
- Observation.status short = 	"preliminary | final | amended +"
- The following features have been included:
 ** canonical URL change (removing '4.0') has been proliferated - affects profiles My Health Record Patient, PractitionerRole with Mandatory Identifier
- intro.md has good introductory material (context, purpose) and implementation guidance, there are no TBDs
 - Known issues is complete, correct, up-to-date and written for an external audience
