### ISSUE TITLE
Create R4 Patient profiles for re-use in common scenarios

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#4]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
This story is to create the Patient profiles for re-use in common scenarios in ci-fhir-r4 on BitBucket and to integrate the profile into the currently available R4 FHIR IGs in ci-fhir-r4. 

## What it actually enables people to do
The profiles will define Agency models for the concept of a patient in exchange usage scenarios, defining fundamental concepts that form a conforming representation of a patient.

## Mockups 
N/A

## How awesome would it be?
Fundamentally awesome - this is the basis of the Agency concept of a Patient in R4 FHIR in clinical data exchange including terminology, identifiers, etc. This contributes to the basic foundation for interoperability, re-use, and optimisation.

## Workarounds
N/A

## Additional context
As part of the development of a profile we need to ensure:
* the R4 HL7 AU Base content used complete and correct - profile | extensions | terminology | namespaces
  * only necessary and sufficient content is present and it is all correct - is everything we need present; is there anything included that we DO NOT want in HL7 AU Base
  * issues that cannot be resolved quickly are raised in HL7 AU GitHub
  * QA for spelling and grammar, 
  * ok against HL7 AU metadata conventions 
  * tested invariant FHIRPath and tested the profile with examples
* design page(s) for each Patient profile(s) are established 
*  Each Patient profile is included in the applicable existing FHIR IGs in ci-fhir-r4 (currently only Event Summary)
   * the profile(s) conform to the metadata conventions

**Comment by dtr-agency** [comment]
Created internal Agency task tickets to create Patient profiles that include support for CALD elements: [Create R4 Patient profiles (My Health Record)](https://jira.digitalhealth.gov.au/browse/CIFMM-3257) & [Create R4 Patient profiles (Patient with Mandatory Identifier)](https://jira.digitalhealth.gov.au/browse/CIFMM-3317). 

It is expected that these patient profiles will Support exchange of CALD (Cultural and Linguistic Diversity) minimum data set #13.

**Comment by RichardTON** [comment]
Completed internal Agency ticket [Create R4 Patient profiles (My Health Record Patient)](https://jira.digitalhealth.gov.au/browse/CIFMM-3317).
More work is needed for the CALD elements biological sex and year of arrival in Australia. 
Requirements for patient contact are not yet clear.

**Comment by robeastwood-agency** [comment]
Commenced work on a new profile for R4 ci-fhir-r4, Patient with Mandatory Identifier

**Comment by robeastwood-agency** [comment]
Progressing internal development of the R4 profile, Patient with Mandatory Identifier. StructureDefinition inclusions are now considered stable and refinements are being made to profile narrative such as implementation guidance and known issues. The set of updates are on track to be merged into master within the week.

**Comment by robeastwood-agency** [comment]
The Patient with Mandatory Identifier profile is now in the latter stages of development and is now in peer review.

**Comment by robeastwood-agency** [comment]
The Patient with Mandatory Identifier profile is now available in master branch as part of the Diagnostic Report IG and the Event Summary IG (via https://github.com/AuDigitalHealth/ci-fhir-r4/commit/9db3ae614c814fcfb081882a9d0b51e7c78a4e72).

Any further issues with the patient profiles will be raised as separate tickets.
