### ISSUE TITLE
Base BodyStructure

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#40]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
This profile is to provide a base model for the concept of a body structure, defining fundamental concepts that form a conforming representation of a body structure when to support electronic exchange of health information between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia. 

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by LB-Agency** [comment]
Work has commenced on this profile, and as such an initial profile 'shell' is now available in the Diagnostic Report IG.

**Comment by dbojicic-agency** [comment]
Additional work done on this profile - very basic ones; a full validation of the profile was not done and introductory content including implementation guidance is not complete:  
- corrected profile URL to "http://ns.electronichealth.net.au/ci/fhir/4.0/StructureDefinition/bodystructure-dh-base-1" (it was incorrect "http://ns.electronichealth.net.au/ci/fhir/StructureDefinition/4.0/bodystructure-dh-base-1")
- canonical URL change (to remove 4.0) - affects My Health  Record Patient
- location binding tightened from 'extensible' to 'required' and removed related known issue
- removed known issues related to morphology binding - current value set is deemed appropriate and binding strength is preferred 
- constrained subject Reference via an invariant

Currently the known issues table for the profile includes the following known issue: 
|Reference|Description|
|----------|-------------|
|locationQualifier (terminology binding)|The binding strength of <a href="http://hl7.org/fhir/R4/valueset-bodystructure-relative-location.html">Bodystructure Location Qualifier</a> (<a href="http://hl7.org/fhir/R4/terminologies.html#example">Example</a>) should be at least extensible in this profile. Consider setting a minimum value set of SNOMED CT to enforce that the code must be SNOMED CT though possibly fixing the system value may be sufficient.|

**Comment by dbojicic-agency** [comment]
Sent for review to @dtr-agency.

**Comment by dtr-agency** [comment]
In internal review with @dtr-agency:

1. The known issue on location qualifier in our GitHub doesn't exist - the profile page still links to the create Base Bodystructure, which will be closed as a result of this PR. Extant issues must have their own GitHub to track that progress and completion of specific concerns.
2. 'inv-dh-bodstr-01: The subject' needs to read 'inv-dh-bodstr-01: The patient' - as the element is named differently in this structure. The FHIRPath also needs to be fixed.
3. There also needs to be the known issue (or invariant) on constraining to have at least location or description - we want tighter than the AU profile

**Comment by dbojicic-agency** [comment]
Made changes:
1. Created GitHub issue [#98](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/98) and updated related IG known issue to reference it
2. Renamed 'subject' to 'patient' in both the invariant description and the expression
3. Added invariant to add a constraint on a body structure to at least have location or description

**Comment by dtr-agency** [comment]
Confirmed 1., 2., and 3. No further comments.
