### ISSUE TITLE
ValueSet - Observation.status - support exchange of Vital Signs

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#42]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue 
We need to support the exchange of observations of vital signs between consumers, healthcare providers, and between consumers and healthcare providers and the My Health Record system infrastructure in Australia.

In order to support this exchange we need to consider a more constrained set of values for the status of the observation than is available by definition.

In support of FHIR specifications the values must be drawn from the required [ObservationStatus](http://hl7.org/fhir/ValueSet/observation-status) ValueSet. Possibly the new ValueSet may contain the codes of "preliminary", "final", "amended", "corrected" excluding "registered", cancelled", entered-in-error" & "unknown". Another possibility is that the Observation.status has a value of  "final".

This constrained set of values may be used directly in CDA implementation guides, or may be supported by [v3 Value Set ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/vs.html).

## What it actually enables people to do
Clarifies to implementers requirements for the state of an observation in the electronic exchange of vital signs between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.
Provision of management of the set of values in a governed manner that is reusable across multiple profiles.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.
This contributes to minimising the risk of inappropriate, invalid or obsolete clinical content.

## Workarounds
There are other means of specifying controls on the membership of values including invariants, or alternatively only implementation guidance could be provided instead of a machine processable format.

## Additional context
This is a part of https://github.com/AuDigitalHealth/ci-fhir-r4/issues/106.

Constraints applied in other FHIR implementation guides:

| Code | Observation.status|
| ------------- | ------------- | 
|[HL7 UK INTEROPen CareConnect FHIR Profiles](https://fhir.hl7.org.uk/StructureDefinition)|"final"|
|[Vital Signs Implementation Guide version 0.1.0]( http://build.fhir.org/ig/HL7/cimi-vital-signs/branches/master/index.html) |[ObservationStatus ](https://www.hl7.org/fhir/valueset-observation-status.html)| 
|[International Patient Summary Implementation Guide](https://build.fhir.org/ig/HL7/fhir-ips/index.html)|  [ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html)| 
|[Canadian Baseline](http://build.fhir.org/ig/HL7-Canada/ca-baseline/branches/master/vitalsigns-profiles.html)| [ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html)| 
|[Finland Kanta Vital Signs](https://www.kanta.fi/en/system-developers/vital-signs) |"final"|
|[CH eTransition of Care](https://fhir.ch/ig/ch-etoc/index.html)| [ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html)| 
|[HL7 Norway Domain profiles](https://simplifier.net/hl7norwaynationalprofiles/~resources?category=Profile)| [ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html)| 
|[US Core Vital Signs Profile](http://hl7.org/fhir/us/core/StructureDefinition-us-core-vital-signs.html)|[ObservationStatus ](https://www.hl7.org/fhir/valueset-observation-status.html)|
|[Switzerland eTransition of Care](https://fhir.ch/ig/ch-etoc/index.html)|[ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html)|

**Comment by davidmckillop** [comment]
In the profile "Simple Other Diagnostic Observation" the element category has been bound (preferred) to [DiagnosticServiceSectionCodes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html); however this value set needs to be investigated for it's suitability.  Another value set may be required and this is being investigated in GitHub #112.

**Comment by dbojicic-agency** [comment]
This ValueSet will be bound as required in Observation.status as part of the Agency Vital Signs models: 
- Respiratory rate
- Heart rate
- Oxygen saturation
- Body temperature
- Body height
- Head circumference
- Body weight
- Body mass index
- Blood pressure

**Comment by dbojicic-agency** [comment]
# Analysis of codes in the required ValueSet

Analysis of possible usage of codes in [ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html)

| Code | Applicable context  | In / Out for vital signs | Rationale | 
| ------------- | ------------- | ------------- | ------------- | 
| registered | Vital Signs | Out | ??|
| preliminary | Vital Signs | In  | ?? |
| final | ALL | In | Supports use case of reporting of results |
| amended | ALL | In | Supports use case of reporting of results |
| corrected | ALL | In | Supports use case of reporting of results |
| cancelled | ALL | Out | Does not serve the use case of reporting of results |
| entered-in-error | ALL | Out | Does not serve the use case of reporting of results |
| unknown | ALL | Out | Does not serve the use case of reporting of results |

_ALL - including social history, clinical findings, vital signs, pathology, diagnostic imaging, other diagnostics_

Analysis of possible usage of codes in [v3 Value Set ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/vs.html)

| Code | Applicable context  | In / Out for vital signs | Rationale | 
| ------------- | ------------- | ------------- | ------------- | 
| normal | ALL  | Out |Too wide; subsumes some codes that are Out.  |
| aborted|  | |  |
| active |  |  |  |
| cancelled |  | |  |
| completed |  |  |  |
| held |  |  |  |
| new |  |  |  |
| suspended |  |  |  |
| nullified|  |  |  |
| obsolete|  |  | 

_ALL - including social history, clinical findings, vital signs, pathology, diagnostic imaging, other diagnostics_

**Comment by dtr-agency** [comment]
Vital signs model handled by AU Base profiles. Observation.status is fixed to "final".
