### ISSUE TITLE
ServiceRequest - Order Details for Diagnostic Imaging Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#43]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
This profile is to represent key elements of clinical relevance of a request for an imaging diagnostic investigation in a diagnostic imaging report context. This profile is intended to support the electronic exchange of diagnostic imaging reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The context of this profile is to support the existing requirements for My Health Record Diagnostic Imaging Report content in a FHIR format and drive CDA-based FHIR. It is also to support requirements for Point-to-Point sharing of diagnostic imaging reports whether in an atomic context or simplified. 

The existing CDA implementation of the My Health Record usage scenario including requirements can be found here: [eHealth Diagnostic Imaging Report v1.2.2](https://developer.digitalhealth.gov.au/specifications/clinical-documents/ep-2560-2017).

Note that the context of this profile is reporting, the requesting of pathology services is not supported by this profile and may in future be the subject of a separate ServiceRequest profile.

## Workarounds
No good ones, potentially use of [AU Diagnostic Service Request](https://build.fhir.org/ig/hl7au/au-fhir-base//StructureDefinition-au-diagnostic-servicerequest.html) could offer some value with terminology but meaningful use is not supported without further derivation and guidance.

## Additional context
[eHealth Diagnostic Imaging Report v1.2.2](https://developer.digitalhealth.gov.au/specifications/clinical-documents/ep-2560-2017)

[View pathology and diagnostic imaging reports](https://www.myhealthrecord.gov.au/for-you-your-family/howtos/view-pathology-and-diagnostic-imaging-reports)

[Diagnostic imaging reports in My Health Record](https://www.myhealthrecord.gov.au/for-healthcare-professionals/howtos/diagnostic-imaging-reports)

**Comment by dtr-agency** [comment]
Work has started on developing a 'shell' ( i.e. must supports, cardinality, fixed values, metadata) StructureDefinition for a Simple Imaging Observation. Progressing content will be in a later phase 2 (i.e. slicing, terminology, invariants).

This shell profile with placeholder introductory content and early known issues will be included in Diagnostic Report FHIR IG.

**Comment by dtr-agency** [comment]
Walked through with Product owner who is happy, now organising internal review.

**Comment by dtr-agency** [comment]
Now in internal review with @vikasmittal-dh

**Comment by dtr-agency** [comment]
Passed internal review; rebuilt Diagnostic Report output and on master to include the shell profile with placeholder introductory content.
Further work expected in a later phase 2 (i.e. slicing, terminology, invariants).

**Comment by dtr-agency** [comment]
The ValueSet design in #60 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
- No 'work in progress' issues remain:
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1" - edited short
   - subject (Reference type too open) - fixed with invariant
   - requester (Reference type too open) - fixed with invariant
- relaxed identifier to be optional (misalignment with eHealth Diagnostic Imaging Report requirements)
- The canonical URL change (removing '4.0') has been proliferated in referenced profiles
- removed wip known issues, added status terminology publication issue 
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product owner walkthrough teed up 17/06.

**Comment by dtr-agency** [comment]
Minor changed in product owner walkthrough to known issues and StructureDefinition.description.

**Comment by dtr-agency** [comment]
Moving to internal review with @vikasmittal-dh

**Comment by dtr-agency** [comment]
Passed internal review.

**Comment by dtr-agency** [comment]
Merged, regenerated output, pushed to GitHub.
