### ISSUE TITLE
Simple Other Diagnostic Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#45]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to represent key elements of clinical relevance (such as diagnostic examination name and clinically relevant date time) to accompany a rich text representation of a diagnostic report as issued by the diagnostic service provider or the electronic exchange of other diagnostic reports (such as echocardiograms) between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by davidmckillop** [comment]
Phase 1 shell profile Simple Other Diagnostic Observation profile been completed.
The shell profile has the basic structure but is missing constraints and terminology bindings.
Profile page in Diagnostics Report FHIR IG includes a list of known issues for the profile.

**Comment by dtr-agency** [comment]
The ValueSet design in #59 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
- No 'work in progress' issues remain:
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1"
   - subject (Reference type too open)
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated in referenced profiles
- intro.md has good introductory material (context, purpose) and implementation guidance, there are no TBDs
- Known issues is complete, correct, up-to-date and written for an external audience

**Comment by dtr-agency** [comment]
Product owner walkthrough - minor changes to known issues and intro.md. Product owner okayed content.

**Comment by dtr-agency** [comment]
Sent for internal review with @RichardTON

**Comment by RichardTON** [comment]
Issues found

1. The introduction phrase"the set of results by of a multi-modality procedure" has an extra "of" or "by", reword
2. Implementation guidance on status has quote marks in fixed width font, while other observation profiles have them in variable font. 
3. Remove must support from Observation.value[x]
4. Issue status (terminology binding) - this should not point to #48 but to #59
5. Issue code (missing terminology) - the thing you need is not AU Base Implementation Guide but ValueSet - Other Diagnostic Reporting

**Comment by dtr-agency** [comment]
1. Done
2. No change - too trivial to fix for this level of draft
3. No. That is an agreed design that was introduced in Phase 1 (please note the confluence design page). There is no defect here. 
4. Done
5. Disagree but changed in a different way. The concern is that part of the known issue was deleted in the last commit. It has been re-instated.

**Comment by RichardTON** [comment]
All OK
