### ISSUE TITLE
Other Diagnostic Reports - fixed category code needed?

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#46]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue 
## Description
There is likely a need for a single fixed code to indicate that this is 'other diagnostics' for a similar use case in the My Health Record to identifying and retrieving 'pathology' and 'imaging'.

## What it actually enables people to do
TBD

## How awesome would it be?
TBD

## Workarounds
TBD

## Additional context
TBD

**Comment by dtr-agency** [comment]
This issue will be handled as part of https://github.com/AuDigitalHealth/ci-fhir-r4/issues/42
