### ISSUE TITLE
Observation - Simple Imaging Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#48]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
Development of a profile to represent key elements of clinical relevance (such as imaging examination name and image date time) to accompany a rich text representation of a diagnostic imaging report as issued by the diagnostic service provider for the electronic exchange of diagnostic imaging reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia. 

The main context of this profile is to support the existing requirements for My Health Record Diagnostic Imaging Report content in a FHIR format and drive CDA-based FHIR. 

The existing CDA implementation including requirements can be found here: [eHealth Diagnostic Imaging Report v1.2.2](https://developer.digitalhealth.gov.au/specifications/clinical-documents/ep-2560-2017).

## What it actually enables people to do
This profile supports the identification of tests performed for a patient enabling an individual to determine if the Diagnostic Imaging Report is of interest but does not directly support reporting of the actual results of the diagnostic imaging tests (see Atomic Diagnostic Imaging Observation for atomic reporting).
The observation may represent the result of a simple test or it may group the set of results produced by a multi-test study. In the latter cases, the observation carries the code of the study / panel and references the individual tests that make up the study / panel as ‘has-member’ child observations.

## Workarounds
No good ones, potentially use of [AU Diagnostic Observation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnostic-observation.html) could offer some value with terminology but meaningful use is not supported without further derivation and guidance.

## Additional context
[eHealth Diagnostic Imaging Report v1.2.2](https://developer.digitalhealth.gov.au/specifications/clinical-documents/ep-2560-2017)

[View pathology and diagnostic imaging reports](https://www.myhealthrecord.gov.au/for-you-your-family/howtos/view-pathology-and-diagnostic-imaging-reports)

[Diagnostic imaging reports in My Health Record](https://www.myhealthrecord.gov.au/for-healthcare-professionals/howtos/diagnostic-imaging-reports)

**Comment by dtr-agency** [comment]
Work has started on developing a 'shell' ( i.e. must supports, cardinality, fixed values, metadata) StructureDefinition for a Simple Imaging Observation. Progressing content will be in a later phase 2 (i.e. slicing, terminology, invariants).

This shell profile with placeholder introductory content and early known issues will be included in Diagnostic Report FHIR IG.

**Comment by dtr-agency** [comment]
Product owner review passed, now submitted for internal review.

**Comment by dtr-agency** [comment]
Internal review picked up missing partOf.reference as 1..1. This has now been fixed and flicked back to review.

**Comment by dtr-agency** [comment]
Passed internal review; rebuilding Diagnostic Report output to commit and push to master.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
- No 'work in progress' issues remain:
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1"
   - subject (Reference type too open)
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated in referenced profiles
- intro.md has good introductory material (context, purpose) and implementation guidance, there are no TBDs
- Known issues is complete, correct, up-to-date and written for an external audience

**Comment by dtr-agency** [comment]
Product owner walkthrough - minor changes to known issues and intro.md. Product owner okayed content.

**Comment by dtr-agency** [comment]
Sent for internal review with @RichardTON

**Comment by RichardTON** [comment]
Issues found:
1. The introduction phrase"the set of results by of a multi-modality procedure" has an extra "of" or "by", reword.
2. Permit codes from the AU Base value set for Observation.code
3. Issue status (terminology binding) - this should not point to #48 but to #59

**Comment by dtr-agency** [comment]
1. Done
2. Disagree with nature of comment but same change outcome. Reverted the change to Observation.code as no change was authorised or desired.
3. Done.

**Comment by RichardTON** [comment]
All OK.
