### ISSUE TITLE
Re-use

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#49]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
In HL7 AU Observation the element bodySite should be bound to https://healthterminologies.gov.au/fhir/ValueSet/body-site-1 (extensible). - refer to #[405](https://github.com/hl7au/au-fhir-base/issues/405)
This terminology is expected to be included in the HL7 AU Base Implementation Guide in AU Diagnostic Observation as a preferred binding and then tightened in this profile when available.
## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dtr-agency** [comment]
@davidmckillop, did you mean to raise this in the HL7 repository?

**Comment by dtr-agency** [comment]
@davidmckillop did you mean to raise this in the HL7 repository?

**Comment by davidmckillop** [comment]
Should have been an au-fhir-base GitHub issue.
