### ISSUE TITLE
Observation - Atomic Imaging Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#51]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to represent an atomic representation of a diagnostic imaging examination observation issued by the diagnostic service provider for the electronic exchange of imaging examination observations between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia. 

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by davidmckillop** [comment]
Work has started on developing a 'shell' ( i.e. must supports, cardinality, fixed values, metadata) StructureDefinition for a Atomic Imaging Observation. Progressing content will be in a later phase 2 (i.e. slicing, terminology, invariants).

This shell profile with placeholder introductory content and early known issues will be included in Diagnostic Report FHIR IG. Progressing via CIFMM-3417.

**Comment by dtr-agency** [comment]
The ValueSet design in #59 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1.

**Comment by dtr-agency** [comment]
In review with @davidmckillop

**Comment by dtr-agency** [comment]
Merged, rebuilt, pushed to GitHub.

**Comment by dtr-agency** [comment]
Merged, rebuilt, pushed to GitHub.
