### ISSUE TITLE
ValueSet - Diagnostic Imaging category terminology for DiagnosticReport

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#55]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
The example value set is too broad for diagnostic imaging reporting - we need a value set that is a constrained value set from that example set [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) that is restricted to the diagnostic imaging appropriate codes. This value set would become required.

Stakeholder feedback is required to determine if Radlex or the output from the work with RSNA and LOINC would be more appropriate than the HL7 [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html).

This change applies to:

DiagnosticReport (My Health Record Diagnostic Imaging Report)
DiagnosticReport (Atomic Diagnostic Imaging Report)

## What it actually enables people to do
It is believed that the HL7 V2 table 0074 [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) is not widely used for Diagnostic Imaging and an agreed industry valueset would be more appropriate.

## How awesome would it be?
It would be great if there was an agreed diagnostic imaging industry valueset for diagnostic report category.   The industry would be more accepting of the profile if their commonly used values were included and this would also increase interoperability.

## Workarounds
The current binding to [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) is [extensible](http://hl7.org/fhir/R4/terminologies.html#extensible) which allows for codes from an alternate code system if there is no applicable concept; however, if this valueset is not the preferred industry used valueset then other codes may be used including those that are valid maps to [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html).  This would add a mixture of codes being used and reduce interoperability.

A work around would be to develop concept maps between the different code systems eg [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html), Radlex or other code system.

**Comment by davidmckillop** [comment]
Content of this ticket is duplicated in #75.  #75  has been closed.

**Comment by davidmckillop** [comment]
The following comment was submitted in a personal email from Dr Nick Ferris (Radiologist) on the 31/8/2020 as part of his personal review/feedback of the FHIR Diagnostic Report FHIR Implementation Guide . Dr Ferris's feedback is published here with his permission.

**Procedure category**
At a less fine-grained level, the Profiles call for the use of a diagnostic report category, referenced to HL7 v2 table 0074, DiagnosticServiceSectionID.  This contains 41 codes, 11 of which pertain to radiology, with a rather arbitrary modality subdivision (4 of the 11 are ultrasound categories). The generic term “imaging report” has been deprecated, while the obsolete (archaic) term NMR remains (change to MRI).  The discussion also mentions the modality field in DICOM as a possible reference for this field.  The latter would be more appropriate for radiology, but is specific to diagnostic imaging (ie, would not be useful for other types of diagnostic report).  Would it be feasible to include subcategories in the “Procedure Category” filed, to allow more targeted categorisation for each discipline ?  Could this be another matter for the HL7 Orders & Observations WG ?
At the very least some revisions to table 0074 seem warranted.

**Comment by davidmckillop** [comment]
Would the use of the [Department of Health](https://www.health.gov.au/health-topics/diagnostic-imaging-scans-and-x-rays)'s definition of “_Diagnostic imaging includes ultrasound, computed tomography (CT) scans, X-rays (including mammography), magnetic resonance imaging (MRI), nuclear medicine imaging and positron emission tomography (PET)._”
Would the Department of Health list be a simpler list than the [DICOM Modality](http://dicomlookup.com/modalities.asp) list and the [HL7 table 0074 (Service Section)](http://hl7.org/fhir/v2/0074/index.html)?

**Comment by jaymeemurdoch** [comment]
Decision to proceed with ValueSets for imaging modality (#101) and anatomic region (#108) instead. This issue is now resolved.
