### ISSUE TITLE
ValueSet - Composition.status - support exchange of appropriate content

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#57]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The feature
## Description
We need to create a more constrained value set for the status element of Composition profiles. The usage scenarios most CI Agency Composition profiles are intended to support are the exchange of current valid electronic healthcare information between healthcare providers, and between healthcare providers and the My Health Record system.

The values must be drawn from the required [CompositionStatus](http://hl7.org/fhir/R4/valueset-composition-status.html) ValueSet. Possibly the new ValueSet may contain the codes of "final" and "amended" and exclude the codes of "preliminary" and "entered-in-error".  

This new constrained ValueSet from [CompositionStatus](http://hl7.org/fhir/R4/valueset-composition-status.html) would be bound to Composition profiles in the forthcoming Diagnostics Report FHIR implementation Guide, and is expected to be used in Continuity of Care (e.g. Discharge Summary).

This does not mean that there will not be a need for systems to mark compositions as 'entered-in-error' or 'withdrawn' but these values are not meaningful in the exchange usage scenarios the Composition profiles are intended to support.

This new constrained ValueSet from [CompositionStatus](http://hl7.org/fhir/R4/valueset-composition-status.html)  would not be used directly in CDA implementation guides; but it may inform the need for Version 2 of the current ValueSet [Australian Healthcare Clinical Document Architecture Document Lifecycle Status](https://healthterminologies.gov.au/fhir/ValueSet/australian-healthcare-cda-document-lifecycle-status-1) which is bound as required in all Agency CDA implementation guides to date.

## What it actually enables people to do
Clarifies to implementers requirements for the state of the composition in an exchange of health information for the purposes of the provision of healthcare. 
Provision of management of the set of values in a governed manner that is reusable across multiple profiles.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.
This contributes to minimising the risk of inappropriate, invalid or obsolete clinical content.

## Workarounds
There are other means of specifying controls on the membership of values including invariants, or alternatively only implementation guidance could be provided instead of a machine processable format. 

## Additional context
- ValueSet implemented in My Health Record system for CDA R2 documents [Australian Healthcare Clinical Document Architecture Document Lifecycle Status](https://healthterminologies.gov.au/fhir/ValueSet/australian-healthcare-cda-document-lifecycle-status-1)
  - codes: withdrawn, interim, final
  - bound to all doc types to date as required
- ConceptMap for above ValueSet to STU3 FHIR CompositionStatus [Australian Healthcare Clinical Document Architecture Document Lifecycle Status to CompositionStatus (HL7 FHIR)](https://healthterminologies.gov.au/fhir/ConceptMap/au-health-cda-lifecycle-status-to-compositionstatus-fhir-1)
- Internal terminology ticket to author and publish the resulting healthterminologies ValueSet in NCTS [FTR-928](https://jira.aws.tooling/browse/FTR-928)
- [PCEHR Overviews, Guides and Conformance Material v1.4](https://developer.digitalhealth.gov.au/specifications/national-infrastructure/ep-2156-2015)

**Comment by dtr-agency** [comment]
This ValueSet when developed will be bound as required in Composition.status as part of:
- Composition (Pathology Report) #19 
- Composition - Other Diagnostic Report #33 
- Composition - Diagnostic Imaging Report #41

**Comment by dtr-agency** [comment]
| Code | Applicable doc type  | In / Out | Description of support | 
| ------------- | ------------- | ------------- | ------------- | 
| preliminary | TBD | TBD | TBD |
| final | TBD | TBD | TBD |
| amended | TBD | TBD | TBD |
| entered-in-error | TBD | TBD | TBD |

**Comment by dtr-agency** [comment]
Note for value set title - document available

**Comment by udaychandrupatla** [comment]
The only values template packages which are in My Health Record will test are below -

<code code="I" displayName="Interim"   codeSystemName="NCTIS Document Status Values" codeSystem="1.2.36.1.2001.1001.101.104.20104"/>
<code code="F" displayName="Final"     codeSystemName="NCTIS Document Status Values" codeSystem="1.2.36.1.2001.1001.101.104.20104"/>
<code code="W" displayName="Withdrawn" codeSystemName="NCTIS Document Status Values" codeSystem="1.2.36.1.2001.1001.101.104.20104"/>

However for PSML stage 2 template packages, we will only check for 

- presence of @code sttribute
- presence of @codeSystem attribute
- presence of @codeSystem attribute value

**Comment by dtr-agency** [comment]
@udaychandrupatla and @vikasmittal-dh, thanks for confirming there are no schematron tests restricting the values for status any further than one of the three codes in in [Australian Healthcare Clinical Document Architecture Document Lifecycle Status](https://healthterminologies.gov.au/fhir/ValueSet/australian-healthcare-cda-document-lifecycle-status-1) in a template package.

**Comment by dtr-agency** [comment]
Suggested outcomes:

1. A new ValueSet for Composition.status containing the codes: 'preferred', 'final', 'amended'
2. A new ValueSet for Composition.status containing the codes: 'final', 'amended'
3. A major version update to the ValueSet for ClinicalDocument/ext:completionCode to remove 'W'
4. Two new ConceptMaps to go between the 1st Composition.status ValueSet and the updated ClinicalDocument/ext:completionCode
5. Two new ConceptMaps to go between the 2nd Composition.status ValueSet and the updated ClinicalDocument/ext:completionCode

**Comment by dtr-agency** [comment]
Outstanding queries to be resolved with BAs: 
Are there any currently supported document types in the My Health Record that allow for the 'update' of a clinical document as in makes use of setId and version to indicate that this is a later version of the same document? 
Or are all updates occuring via superseding to a 'newer' clinical document.

**Comment by LB-Agency** [comment]
I would suggest that a new value set be created for document statuses of 'F' and 'I'. The purpose and scope of the value set has been significantly changed and no longer represents the same spectrum of statuses. It now only covers statuses of "active" or "in effect" compositions. 

Do the usage scenarios of CDA not cover making amendments or corrections? This could be supported with a concept addition to https://healthterminologies.gov.au/fhir/CodeSystem/nctis-document-status-values-1.

I was also found wondering what the usage scenarios were and why "entered-in-error" and "W" are outside the scope of them. Are compositions never cancelled but only superseding compositions may be sent? Thanks.

**Comment by dtr-agency** [comment]
# ConceptMap Design Notes
## 4. Two new ConceptMaps to go between the 1st Composition.status ValueSet and the updated ClinicalDocument/ext:completionCode
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | TBD | 
| name | TBD |
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/TBD-1 |
| version | 1.0.0 |
| description | TBD | 
| sourceCanonical | TBD | 
| targetCanonical | TBD | 
| group | TBD | 

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | TBD | 
| name | TBD |
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/TBD-1 |
| version | 1.0.0 |
| description | TBD | 
| sourceCanonical | TBD | 
| targetCanonical | TBD | 
| group | TBD | 

## 5. Two new ConceptMaps to go between the 2nd Composition.status ValueSet and the updated ClinicalDocument/ext:completionCode

| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | TBD | 
| name | TBD |
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/TBD-1 |
| version | 1.0.0 |
| description | TBD | 
| sourceCanonical | TBD | 
| targetCanonical | TBD | 
| group | TBD | 

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | TBD | 
| name | TBD |
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/TBD-1 |
| version | 1.0.0 |
| description | TBD | 
| sourceCanonical | TBD | 
| targetCanonical | TBD | 
| group | TBD |

**Comment by dtr-agency** [comment]
Designs in review with Terminology Analyst.

**Comment by dtr-agency** [comment]
ConceptMap @url is too long; has to be max 64 and is currently 81.
Current
https://healthterminologies.gov.au/fhir/ConceptMap/nctis-document-available-status-values-to-compositionstatus-document-available-1
https://healthterminologies.gov.au/fhir/ConceptMap/compositionstatus-document-available-to-nctis-document-available-status-values-1

Preferred to become
https://healthterminologies.gov.au/fhir/ConceptMap/nctis-document-available-to-compositionstatus-document-available-1
https://healthterminologies.gov.au/fhir/ConceptMap/compositionstatus-document-available-to-nctis-document-available-1

**Comment by dtr-agency** [comment]
Terminology Analyst review identified issues with Concept Map canonical url length and use of conventions in name field.

Name field has been removed and will be defined by terminology analyst as part of authoring service. Canonical url trimmed; may need more.

**Comment by dtr-agency** [comment]
Now accepted. Moving to publication schedule.

**Comment by dtr-agency** [comment]
This issue has been shifted to 'complete'; publication of the content in NCTS is pending release of NTS 2.0.

**Comment by dtr-agency** [comment]
To remain open until publication is confirmed.

**Comment by dtr-agency** [comment]
NCTS 2.0 is now live with [CompositionStatus Document Available](https://healthterminologies.gov.au/fhir/ValueSet/compositionstatus-document-available-1). 

The other two value sets are still to be published; this issue will remain open.

**Comment by davidmckillop** [comment]
All value sets and concept maps have been created and are available in the production system.  Contents have been confirmed.
