### ISSUE TITLE
ValueSet - DiagnosticReport.status - support exchange of Diagnostic Reports

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#58]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The feature
## Description
We need to create a more constrained value set for the status element of DiagnosticReport profiles to support exchange of diagnostic reports issued by diagnostic service providers for the electronic exchange of diagnostic reports (e.g. pathology, imaging, specialist and other) between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The usage scenarios expects a meaningful patient-centric snapshot, i.e. one or more investigations have been performed and there is some reported information that is meaningful to share between healthcare providers, and between healthcare providers and the My Health Record system to support provision of healthcare.

The values must be drawn from the required [DiagnosticReportStatus](http://hl7.org/fhir/R4/valueset-diagnostic-report-status.html) ValueSet. Possibly the new ValueSet may contain the codes of "partial", "preliminary", "final", "amended", "corrected", "appended" and exclude "registered", cancelled", "entered-in-error" & "unknown".  

This ValueSet would be bound to DiagnosticReport profiles in the forthcoming Diagnostics Report FHIR implementation Guide, and may be used in other implementation guides that contain DiagnosticReport profiles.

## What it actually enables people to do
Clarifies to implementers requirements for the state of a diagnostic report in the electronic exchange of diagnostic imaging reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.
Provision of management of the set of values in a governed manner that is reusable across multiple profiles.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.
This contributes to minimising the risk of inappropriate, invalid or obsolete clinical content.

## Workarounds
There are other means of specifying controls on the membership of values including invariants, or alternatively only implementation guidance could be provided instead of a machine processable format. 

## Additional context
- ValueSet implemented in My Health Record system for eHealth Pathology Report and eHealth Diagnostic Imaging Report CDA R2 documents is [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html)
- ValueSet implemented for DiagnosticReports in Continuity of Care, e.g. Discharge Summary (DS), Event Summary (ES), eReferral (Ref), Service Referral (SR), Specialist Letter (SL) is is the CodeSystem [NCTIS Result Status Values]
    - note that Service Referral also allows [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html)
    - terminology only enforced at 3B
- Internal terminology ticket to author and publish the resulting healthterminologies ValueSet in NCTS [FTR-933](https://jira.aws.tooling/browse/FTR-933)

**Comment by dtr-agency** [comment]
This ValueSet when developed will be bound as required in Observation.status as part of:
- [Pathology Report with atomic content #21](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/21)
- [My Health Record Pathology Report #23](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/23)
- [My Health Record Other Diagnostic Report #44](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/44)
- [DiagnosticReport - Atomic Other Diagnostic Report #53](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/53)
- [DiagnosticReport - My Health Record Diagnostic Imaging Report #47](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/47)
- [DiagnosticReport - Atomic Diagnostic Imaging Report #50](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/50)

**Comment by dtr-agency** [comment]
# Analysis of codes in the required value sets
Analysis of possible usage of codes in [CompositionStatus](http://hl7.org/fhir/R4/valueset-composition-status.html) 
| Code | Applicable doc type  | In / Out | Rationale | 
| ------------- | ------------- | ------------- | ------------- | 
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |

**Comment by dtr-agency** [comment]
@davidmckillop, can you please review the above analysis of codes against the three domains?

**Comment by davidmckillop** [comment]
@dtr-agency - I agree with your analysis of the codes to be included in/out for the diagnostic report use case for the above 3 domains.

**Comment by dtr-agency** [comment]
Suggested outcomes:
1.	A new ValueSet for DiagnosticReport.status containing the codes: ‘partial’, ‘preliminary', ‘final', ‘amended’, ‘corrected’, ’appended’
2.	Analysis of existing and legacy value sets in CDA with recommendations for a path forwards

**Comment by dtr-agency** [comment]
# ValueSet Design Notes
## 1. A new ValueSet for DiagnosticReport.status containing the codes: 'preliminary', 'final', 'amended', ‘corrected’, ‘appended’
ValueSet    element | Suggested    value
-- | --
title | DiagnosticReportStatus Report   Available
canonical url | https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1
version | 1.0.0
description | The DiagnosticReportStatus Report   Available value set includes values that may be used to represent the status   of a diagnostic report that is available for electronic exchange of health   information between healthcare providers, and between healthcare providers   and the My Health Record system in Australia.
compose | system: "http://hl7.org/fhir/composition-status";   concept: [code: "preliminary"; code: "final"; code:   "amended"; code: "corrected"; code: "appended"]

Associated FHIR Terminology Request: [FTR-953](https://jira.aws.tooling/browse/FTR-953)

**Comment by dtr-agency** [comment]
@davidmckillop - ready for product owner walkthrough.

**Comment by LB-Agency** [comment]
Review of DiagnosticReportStatus Report Available value set.

I agree with the analysis of codes for this use case. Only comment is to update the design table so compose includes, "system": "http://hl7.org/fhir/diagnostic-report-status"; "version": "4.0.1"; "code": "partial".

NCTS resources will contain version specific references to external content unless normative and known to not have future backwards incompatible changes introduced.

**Comment by dtr-agency** [comment]
[HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html) vs [NCTIS Result Status Values](https://healthterminologies.gov.au/fhir/CodeSystem/nctis-result-status-values-1) vs [DiagnosticReportStatus](http://hl7.org/fhir/R4/valueset-diagnostic-report-status.html)

**Comment by dtr-agency** [comment]
@LB-Agency, please review the above discussion of applicability of candidate terminology in CDA.

**Comment by davidmckillop** [comment]
@dtr-agency - I agree with the recommendations described above that :
1. the concept of DiagnosticReport status in FHIR-based CDA is supported with [DiagnosticReportStatus](http://hl7.org/fhir/R4/valueset-diagnostic-report-status.html) using the proposed  [DiagnosticReportStatus Report Available](https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1) 
2. ConceptMaps describing relationships between [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html) and the proposed [DiagnosticReportStatus Report Available](https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1) are published to provide clarity on code equivalence and provide a path forwards for the transition of affected legacy materials.
3. ConceptMaps describing relationships between [NCTIS Result Status Values](https://healthterminologies.gov.au/fhir/CodeSystem/nctis-result-status-values-1) (using the forthcoming ValueSet) and the proposed [DiagnosticReportStatus Report Available](https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1) are published to provide clarity on code equivalence and provide a path forwards for the transition of affected legacy materials.

**Comment by LB-Agency** [comment]
Review comments:
* Agree with the analysis that the most appropriate and correct values to use in the future are from DiagnosticReportStatus and should be from DiagnosticReportStatus Report Available value set.
* Agree with the proposed scope of concept maps to support authoring systems exchange the DiagnosticReportStatus values. It will be important to be clear in the concept map description the purpose and intended usage so that the stated concept equivalence is understood, particularly in the case of HL7 V2 Table 0123.

**Comment by dtr-agency** [comment]
## Early design notes on ConceptMaps
_NOTE: These will be progressed via internal terminology tasks as per the BAU publication schedule; this GitHub issue will not be kept up to date. This content has been included here as an indication of the initial direction of this content._

### 2. Two new ConceptMaps to go between [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html) and the proposed [DiagnosticReportStatus Report Available](https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1)
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | DiagnosticReportStatus Report Available to v2 RESULT STATUS - OBR  | 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/diagnosticreportstatus-report-avail-to-v2-result-status-obr-1 |
| version | 1.0.0 |
| description | The DiagnosticReportStatus Report Available to v2 RESULT STATUS - OBR concept map defines relationships from the concepts in the DiagnosticReportStatus Report Available value set to the concepts in the v2 RESULT STATUS - OBR value set.| 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1 | 
| targetCanonical | http://terminology.hl7.org/ValueSet/v2-0123 | 
| group | [code: "partial"; target code: "A"; equivalence: "narrower"; comment: "partial subsumes but is not limited to the concept of some but not all results available"] 
[code: "partial"; target code: "R"; equivalence: "narrower"; comment: "partial subsumes but is not limited to the concept of results stored but not yet verified"]
[code: "preliminary"; target code: "P"; equivalence: "equivalent"] 
[code: "final"; target code: "F"; equivalence: "equivalent"] 
 [code: "amended"; target code: "C"; equivalence: "narrower"; comment: "amended subsumes but is not limited to the concept of correction"] 
 [code: "corrected"; target code: "C"; equivalence: "equivalent"]  
[code: "appended"; equivalence: "unmatched"]  | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1058](https://jira.aws.tooling/browse/FTR-1058)

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | v2 RESULT STATUS - OBR to DiagnosticReportStatus Report Available| 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/v2-result-status-obr-to-diagnosticreportstatus-report-avail-1 |
| version | 1.0.0 |
| description | The v2 RESULT STATUS - OBR to DiagnosticReportStatus Report Available concept map defines relationships from the concepts in the v2 RESULT STATUS - OBR value set to the concepts in the DiagnosticReportStatus Report Available value set. This mapping is applicable where the v2 RESULT STATUS - OBR value set has been bound to a report level status element. This concept map may be used to support transitioning legacy materials from a conformant Agency CDA template to a FHIR-driven CDA template. | 
| sourceCanonical | http://terminology.hl7.org/ValueSet/v2-0123| 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1 | 
| group | [code: "A"; target code: "partial"; equivalence: "wider"] 
[code: "C"; target code: " corrected"; equivalence: "equivalent"]
[code: "F"; target code: "final"; equivalence: "equivalent"] 
[code: "I"; equivalence: "unmatched"]
[code: "M"; target code: "preliminary"; equivalence: "wider"]
[code: "N"; equivalence: "unmatched"]
[code: "O”; equivalence: "unmatched"]
[code: "P"; target code: "preliminary"; equivalence: "equivalent"]
[code: "R"; target code: "preliminary"; equivalence: "equivalent"] 
[code: "S"; equivalence: "unmatched"]
[code: "X"; equivalence: "unmatched"]
[code: "Y"; equivalence: "unmatched"]
[code: "Z”; equivalence: "unmatched"] | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1063](https://jira.aws.tooling/browse/FTR-1063)

### 4. Two new ConceptMaps to go between DiagnosticReportStatus Report Available and [NCTIS Result Status Values](https://www.hl7.org/fhir/v2/0085/index.html)
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | DiagnosticReportStatus Report Available to NCTIS Result Status Values  | 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/diagnosticreportstatus-report-avail-to-v2-result-status-obr -1 |
| version | 1.0.0 |
| description | The DiagnosticReportStatus Report Available to NCTIS Result Status Values concept map defines relationships from the concepts in the DiagnosticReportStatus Report Available value set to the concepts in the NCTIS Result Status Values value set. This mapping is applicable where the NCTIS Results Status Values value set has been bound to a report level status element. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/nctis-result-status-values-1 | 
| group | [code: "partial"; target code: "2"; equivalence: "equivalent"] 
 [code: "preliminary"; target code: "2"; equivalence: "wider"] 
[code: "final"; target code: "3"; equivalence: "equivalent"] 
 [code: "amended"; target code: "4"; equivalence: " equivalent"] 
 [code: "corrected"; target code: "4"; equivalence: "wider"]  
[code: "appended"; target code: "4"; equivalence: "wider"]  | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1048](https://jira.aws.tooling/browse/FTR-1048)

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | NCTIS Result Status Values to DiagnosticReportStatus Report Available| 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/v2-result-status-obr-to-diagnosticreportstatus-report-avail-1 |
| version | 1.0.0 |
| description | The NCTIS Result Status Values to DiagnosticReportStatus Report Available concept map defines relationships from the concepts in the NCTIS Result Status Values value set to the concepts in the DiagnosticReportStatus Report Available value set. This mapping is applicable where the NCTIS Results Status Values value set has been bound to a report level status element. This concept map may be used to support transitioning legacy materials from a conformant Agency CDA template to a FHIR-driven CDA template. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/nctis-result-status-values-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1 | 
| group | [code: "1"; equivalence: "unmatched"] 
[code: "2"; target code: "partial"; equivalence: "equivalent"] 
[code: "3"; target code: "final"; equivalence: " equivalent "] 
[code: "4"; target code: "amended"; equivalence: "equivalent"] 
[code: "5"; equivalence: "unmatched"] | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1053](https://jira.aws.tooling/browse/FTR-1053)

**Comment by dtr-agency** [comment]
This issue has been shifted to 'complete'; publication of the content in NCTS is pending release of NTS 2.0.

**Comment by dtr-agency** [comment]
To remain open until publication is confirmed.

**Comment by dtr-agency** [comment]
NCTS 2.0 is now live with [DiagnosticReportStatus Report Available](https://api.healthterminologies.gov.au/integration/R4/fhir/ValueSet/diagnosticreportstatus-report-available-1). 

ConceptMaps are in the authoring and publication schedule for later this year.
