### ISSUE TITLE
ValueSet - Observation.status - support exchange of diagnostic reports

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#59]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The feature
## Description
We need to create a more constrained value set for the status element of Observation profiles to support exchange of diagnostic reports issued by diagnostic service providers for the electronic exchange of diagnostic reports (e.g. pathology, imaging, specialist and other) between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The usage scenarios expects a meaningful patient-centric snapshot, i.e. one or more investigations have been performed and there is some reported information that is meaningful to share between healthcare providers, and between healthcare providers and the My Health Record system to support provision of healthcare.

The values must be drawn from the required [ObservationStatus](http://hl7.org/fhir/R4/valueset-observation-status.html) ValueSet. Possibly the new ValueSet may contain the codes of "preliminary", "final", "amended", "corrected" excluding "registered", cancelled", entered-in-error" & "unknown". 

This ValueSet would be bound to Observation profiles in the forthcoming Diagnostics Report FHIR implementation Guide, and in Continuity of Care including Discharge Summary, Event Summary, Specialist Letter.

## What it actually enables people to do
Clarifies to implementers requirements for the state of an observation in the electronic exchange of diagnostic reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.
Provision of management of the set of values in a governed manner that is reusable across multiple profiles.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.
This contributes to minimising the risk of inappropriate, invalid or obsolete clinical content.

## Workarounds
There are other means of specifying controls on the membership of values including invariants, or alternatively only implementation guidance could be provided instead of a machine processable format. 

## Additional context
- ValueSet implemented in My Health Record system for eHealth Pathology Report and eHealth Diagnostic Imaging Report CDA R2 documents is [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html)
- ValueSet implemented in My Health Record system for CDA R2 documents HL7 in Continuity of Care documents incl. Discharge Summary (DS), Event Summary (ES), eReferral (Ref), Service Referral (SR), Specialist Letter (SL) is the CodeSystem [NCTIS Result Status Values](https://healthterminologies.gov.au/fhir/CodeSystem/nctis-result-status-values-1) 
      - note that Service Referral also allows [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html)
      - terminology only enforced at 3B
- Additionally fixed values for status from the ValueSet [v3 Code System ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/vs.html) have been implemented in My Health Record system for CDA R2 documents HL7 in Continuity of Care documents incl. Discharge Summary (DS), Event Summary (ES), eReferral (Ref), Service Referral (SR), Specialist Letter (SL):
      - used 'completed'
      - extant known issue on DCM-based CDA that the statusCode element and this value set should be used in CDA
- Internal terminology ticket to author and publish the resulting healthterminologies ValueSet in NCTS [FTR-938](https://jira.aws.tooling/browse/FTR-938)

**Comment by dtr-agency** [comment]
This ValueSet when developed will be bound as required in Observation.status as part of:
- [Observation - Atomic Imaging Observation #51](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/51)
- [Observation - Simple Imaging Observation #48](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/48)
- [Simple Other Diagnostic Observation #45](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/45)
- [Observation - Atomic Other Diagnostic Observation #36](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/36)
- [Simple Pathology Observation #20](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/20)
- [Atomic Pathology Observation](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/30)

**Comment by dtr-agency** [comment]
# Analysis of codes in the required value sets
Analysis of possible usage of codes in [ObservationStatus](https://www.hl7.org/fhir/valueset-observation-status.html) 
| Code | Applicable doc type  | In / Out | Rationale | 
| ------------- | ------------- | ------------- | ------------- | 
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |

**Comment by dtr-agency** [comment]
@davidmckillop, can you please review the above analysis of codes against the three diagnostic domains?

**Comment by davidmckillop** [comment]
@dtr-agency - I agree with your analysis of in/out codes listed above for the 3 diagnostic domains (pathology, diagnostic imaging and other diagnotics).

**Comment by dtr-agency** [comment]
This issue is scoped specifically to support exchange of diagnostic reports so only the diagnostic context work will be progressed.
Suggested outcomes:
1.	A new ValueSet for Observation.status containing the codes: ‘preliminary', ‘final', ‘amended’, ‘corrected’
2.	Analysis of existing and legacy value sets in CDA with recommendations for a path forwards

**Comment by dtr-agency** [comment]
# ValueSet Design Notes
## 1. A new ValueSet for Observation.status containing the codes: 'preliminary', 'final', 'amended', ‘corrected’

ValueSet    element | Suggested    value
-- | --
title | ObservationStatus Result   Available
canonical url | https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1
version | 1.0.0
description | The ObservationStatus Result   Available value set includes values that may be used to represent the status   of an observation that indicates a result is available for electronic   exchange of health information between healthcare providers, and between   healthcare providers and the My Health Record system in Australia.
compose | system: "http://hl7.org/fhir/composition-status";   concept: [code: "preliminary"; code: "final"; code:   "amended"; code: "corrected"]

Associated FHIR Terminology Request: [FTR-938](https://jira.aws.tooling/browse/FTR-938)

**Comment by dtr-agency** [comment]
@davidmckillop - ready for product owner walkthrough of proposed value set design.

**Comment by LB-Agency** [comment]
Review of ObservationStatus Result Available value set.

I agree with the analysis of codes for this use case. Only comment is to update the design table so compose includes, "system": "http://hl7.org/fhir/observation-status".

**Comment by dtr-agency** [comment]
### Notes relating to the extant known issue on DCM-based CDA that the statusCode element and [v3 Code System ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/vs.html)  should be used in CDA.

v3 ActStatus is not recommended. The FHIR element Observation.status captures different semantics to observation/statusCode. Observation.status is about the status of the result value whereas the statuscode element in CDA is defined possible states of an Act, as defined by the Act class state. It reflects the state of the activity. In the case of an Observation, this is the status of the activity of observing. Similar but not the same.

**Comment by dtr-agency** [comment]
[HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html) vs [NCTIS Result Status Values](https://healthterminologies.gov.au/fhir/CodeSystem/nctis-result-status-values-1) vs [ObservationStatus](http://hl7.org/fhir/R4/valueset-observation-status.html)

**Comment by dtr-agency** [comment]
@LB-Agency, please review the above discussion of applicability of candidate terminology in CDA.

**Comment by davidmckillop** [comment]
> ### Notes relating to the extant known issue on DCM-based CDA that the statusCode element and [v3 Code System ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/vs.html) should be used in CDA.
> v3 ActStatus is not recommended. The FHIR element Observation.status captures different semantics to observation/statusCode. Observation.status is about the status of the result value whereas the statuscode element in CDA is defined possible states of an Act, as defined by the Act class state. It reflects the state of the activity. In the case of an Observation, this is the status of the activity of observing. Similar but not the same.
> 
> When mapping the element Observation.status into CDA, codes from [v3 Code System ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/vs.html) should not be used.
> 
> ### Notes relating to applicability of [v2 OBSERVATION RESULT STATUS v2.0085](https://www.hl7.org/fhir/v2/0085/index.html)
> [v2 OBSERVATION RESULT STATUS](https://www.hl7.org/fhir/v2/0085/index.html) is not recommended. This terminology cannot be used in FHIR, and has not been included in Agency CDA implementation guides to date.
> 
> There is significant equivalence between the FHIR element Observation.status and the codes in [v2 OBSERVATION RESULT STATUS](https://www.hl7.org/fhir/v2/0085/index.html) at an individual level for results of an observation resulting from a procedure - this terminology is not suitable for all observations and contains some workflow codes.
> 
> However this is less equivalent at the study or panel Observation where [HL7 Version 2 Table 0123](https://www.hl7.org/fhir/v2/0123/index.html) is more applicable (and has been included in some Agency CDA implementation guides).
> 
> When mapping the element Observation.status into CDA, codes from [v2 OBSERVATION RESULT STATUS](https://www.hl7.org/fhir/v2/0085/index.html) are not suitable to be used unless a profile specifically for an 'individual test observation' / 'v2 message segment' is requested.
> 
> @davidmckillop - please comment on the above notes.

**Comment by davidmckillop** [comment]
@dtr-agency - I agree with the above conclusion and recommendations, including:
1.  The concept of Observation status in FHIR-based CDA is supported with [ObservationStatus](http://hl7.org/fhir/R4/valueset-observation-status.html) using the proposed  [ObservationStatus Result Available](https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1)
2. Concepts maps are created for HL7 [Table 0085](https://www.hl7.org/fhir/v2/0085/index.html) (HL7 V2 OBX-11 Observation result status and [Table 0123](https://www.hl7.org/fhir/v2/0123/index.html) HL7 V2 OBR-25 Results status) as these will be commonly used by pathology providers using HL7 V2 messaging and exisyinh CDA documents.

**Comment by LB-Agency** [comment]
@dtr-agency - In general I agree with the proposal, but some additional clarity on Recommendation 5 would be great. 

It is understood the rationale for the 2 value sets a 2 sets of concept maps supporting translations both ways between CDA and FHIR (HL7 V2 Table 0123-ObservationStatus and NCTIS Result Status Values-ObservationStatus).

What is the purpose of the set between HL7 V2 Table 0085-ObservationStatus? Is this for implementers that require transform from V2 to FHIR rather than supporting a legacy Agency CDA spec? Also, is there a proposal for a HL7 V2 Table 0085 value set?

**Comment by dtr-agency** [comment]
@LB-Agency, there is no recommendation for a ValueSet of Table 0085-ObservationStatus from this piece of work. @davidmckillop, can you provide more information for @LB-Agency on the value of the concept maps between HL7 V2 Table 0085-ObservationStatus.

**Comment by davidmckillop** [comment]
@LB-Agency , @dtr-agency ,  Regarding requirement 5 above:
"ConceptMaps describing relationships between the yet to be designed value set of HL7 Version 2 Table 0085 and the proposed ObservationStatus Result Available are published to provide clarity on code equivalence and provide a path forwards for the transition of affected legacy materials."
Background:
All current and past pathology messaging is done using HL7 V2.x which has observations in OBX segments where the Observation-status is captured in OBX-25 (Result status) which uses [HL7 Table 0123](http://hl7.org/fhir/R4/v2/0123/index.html).  All the current CDA and Agency specifications do not refer to table 0123, which was probably an oversight.  
Given the prevalence of Table 0123 in current HL7 V2.x messaging and the likely way forward for pathology is to map the current V2 message to FHIR content, then it would be useful to have a concept map from HL7 table 0123 to the FHIR content.  If nothing else to make the path easier for pathology systems to navigate it would be useful to have a table 0123 concept map to the FHIR valueset.

**Comment by LB-Agency** [comment]
Thanks @davidmckillop. So the use case describes one concept map going from V2(table 0085) to FHIR(ObservationStatus) so systems can author and send FHIR content. There's nothing suggesting systems will need to generate V2 messages from FHIR. Is that correct?

**Comment by davidmckillop** [comment]
Hi @LB-Agency ,  yes the use case is to assist the V2 messages to be translated into FHIR content.  I do not envisage a reverse map of FHIR to V2.

**Comment by LB-Agency** [comment]
Ok that's cleared things up. Thanks. I'm happy to accept this now.

**Comment by dtr-agency** [comment]
## Early design notes on ConceptMaps
_NOTE: These will be progressed via internal terminology tasks as per the BAU publication schedule; this GitHub issue will not be kept up to date. This content has been included here as an indication of the initial direction of this content._

## 4. Two new ConceptMaps to go between the two new ValueSets
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | ObservationStatus Result Available to v2 RESULT STATUS – OBR Result Available | 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/observstatus-result-avail-to-v2-result-status-obr-result-avail-1 |
| version | 1.0.0 |
| description | The ObservationStatus Result Available to v2 RESULT STATUS – OBR Result Available concept map defines relationships from the concepts in the ObservationStatus Result Available value set to the concepts in the v2 RESULT STATUS – OBR Result Available value set. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/v2-result-status-obr-result-available-1 | 
| group | [code: "preliminary"; target code: "P"; equivalence: "equivalent"] [code: "final"; target code: "F"; equivalence: "equivalent"]  [code: "amended"; target code: "C"; equivalence: "narrower"; comment: "amended subsumes but is not limited to the concept of correction"] [code: "amended"; target code: "F"; equivalence: "inexact"; comment: "TBD"] [code: "corrected"; target code: "C"; equivalence: "equivalent"]  | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1068](https://jira.aws.tooling/browse/FTR-1068)

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | v2 RESULT STATUS – OBR Result Available to ObservationStatus Result Available| 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/v2-result-status-obr-result-avail-to-observstatus-result-avail-1 |
| version | 1.0.0 |
| description | The v2 RESULT STATUS – OBR Result Available to ObservationStatus Result Available concept map defines relationships from the concepts in the v2 RESULT STATUS – OBR Result Available value set to the concepts in the ObservationStatus Result Available value set. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/v2-result-status-obr-result-available-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1 | 
| group | [code: "A"; target code: "preliminary"; equivalence: "?"] [code: "C"; target code: " corrected"; equivalence: "equivalent"] [code: "F"; target code: "final"; equivalence: "?"] [code: "M"; target code: "preliminary"; equivalence: "wider"] [code: "P"; target code: "preliminary"; equivalence: "?"] [code: "R"; target code: "preliminary"; equivalence: "wider"] | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1073](https://jira.aws.tooling/browse/FTR-1073)

## 5. ConceptMap to go between ObservationStatus Result Available and [v2 OBSERVATION RESULT STATUS v2.0085](https://www.hl7.org/fhir/v2/0085/index.html)
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | v2 OBSERVATION RESULT STATUS to ObservationStatus Result Available| 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/v2-obs-result-status-to- observstatus-result-avail-1 |
| version | 1.0.0 |
| description | The v2 OBSERVATION RESULT STATUS to ObservationStatus Result Available concept map defines relationships from the concepts in the v2 OBSERVATION RESULT STATUS value set to the concepts in the ObservationStatus Result Available value set. | 
| sourceCanonical | http://terminology.hl7.org/ValueSet/v2-0085 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1 | 
| group | [code: "A"; target code: "amended "; equivalence: "wider"] [code: "B"; target code: "amended"; equivalence: "wider"] [code: "C"; target code: "corrected"; equivalence: "equivalent"] [code: "D"; equivalence: "unmatched"] [code: "F"; target code: "final"; equivalence: "equivalent"][code: "I"; target code: " registered"; equivalence: "inexact"; comment: "TBD"] [code: "N"; target code: " cancelled "; equivalence: "inexact"; comment: "TBD"] [code: "O"; equivalence: "unmatched"] [code: "P"; target code: "preliminary"; equivalence: "equivalent "] [code: "R"; target code: "preliminary"; equivalence: "wider"] [code: "S"; target code: " preliminary"; equivalence: "wider"] [code: "U"; target code: "final"; equivalence: "TBD"] [code: "V"; target code: "final"; equivalence: "equivalent"] [code: "W"; target code: "entered-in-error"; equivalence: "inexact"] [code: "X"; target code: "cancelled"; equivalence: "inexact"; comment: "TBD"] | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1033](https://jira.aws.tooling/browse/FTR-1033)

## 6. Two new ConceptMaps to go between ObservationStatus Result Available and [NCTIS Result Status Values](https://www.hl7.org/fhir/v2/0085/index.html)
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | ObservationStatus Result Available to NCTIS Result Status Values  | 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/observstatus-result-avail-to-nctis-result-status-values-1 |
| version | 1.0.0 |
| description | The ObservationStatus Result Available to NCTIS Result Status Values concept map defines relationships from the concepts in the ObservationStatus Result Available value set to the concepts in the NCTIS Result Status Values value set. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/nctis-result-status-values-1 | 
| group | [code: "preliminary"; target code: "2"; equivalence: "equivalent"] [code: "final"; target code: "3"; equivalence: "equivalent"]  [code: "amended"; target code: "4"; equivalence: " equivalent"]  [code: "corrected"; target code: "4"; equivalence: "wider"]  | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1038](https://jira.aws.tooling/browse/FTR-1038)

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | NCTIS Result Status Values to ObservationStatus Result Available| 
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/nctis-result-status-values-to-observstatus-result-avail-1 |
| version | 1.0.0 |
| description | The NCTIS Result Status Values to ObservationStatus Result Available concept map defines relationships from the concepts in the NCTIS Result Status Values value set to the concepts in the ObservationStatus Result Available value set. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/nctis-result-status-values-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1 | 
| group | [code: "1"; equivalence: "unmatched"] [code: "2"; target code: "preliminary"; equivalence: "equivalent"] [code: "3"; target code: "final"; equivalence: " equivalent "] [code: "4"; target code: "amended"; equivalence: "equivalent"] [code: "5"; equivalence: "unmatched"] | 

_The content in group is a suggested starting point; review and analysis by a terminology analyst when authoring is necessary._

Associated FHIR Terminology Request: [FTR-1043](https://jira.aws.tooling/browse/FTR-1043)

**Comment by dtr-agency** [comment]
This issue has been shifted to 'complete'; publication of the content in NCTS is pending release of NTS 2.0.

**Comment by dtr-agency** [comment]
To remain open until publication is confirmed.

**Comment by dtr-agency** [comment]
NCTS 2.0 is now live with [ObservationStatus Result Available](https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1). 

The other value set is still to be published; this issue will remain open.

**Comment by dtr-agency** [comment]
Publication now complete.
