### ISSUE TITLE
ValueSet - ServiceRequest.status - support exchange of diagnostic reports

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#60]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The feature
## Description
We need to create a more constrained value set for the status element of ServiceRequest profiles to support exchange of diagnostic reports issued by diagnostic service providers for the electronic exchange of diagnostic reports (e.g. pathology, imaging, specialist and other) between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The usage scenarios expects a meaningful patient-centric snapshot, i.e. one or more investigations have been performed and there is some reported information that is meaningful to share between healthcare providers, and between healthcare providers and the My Health Record system to support provision of healthcare.

The values must be drawn from the required [RequestStatus](http://hl7.org/fhir/R4/valueset-request-status.html) ValueSet. Possibly the new ValueSet may contain the codes of "active", "on-hold" & "completed" and excluding "draft", "revoked", "entered-in-error" and "unknown". 

This ValueSet would be bound to ServiceRequest profiles in the forthcoming Diagnostics Report FHIR implementation Guide, and any other ServiceRequest profile that is in a reporting rather than requesting context.

## What it actually enables people to do
Clarifies to implementers requirements for the state of a order for a diagnostic service in the electronic exchange of diagnostic reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.
Provision of management of the set of values in a governed manner that is reusable across multiple profiles.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.
This contributes to minimising the risk of inappropriate, invalid or obsolete clinical content.

## Workarounds
There are other means of specifying controls on the membership of values including invariants, or alternatively only implementation guidance could be provided instead of a machine processable format. 

## Additional context
- ValueSet implemented in My Health Record system for Continuity of Care (Referral, Discharge Summary, Event Summary) CDA R2 documents [v3.ActStatus](http://hl7.org/fhir/R4/v3/ActStatus/cs.html) - expected to remain required in CDA to map into act/statusCode
- element not directly supported in eHealth Patholgy Report and eHealth Diagnostic Imaging Report; status is implied by the inFulfillmentOf relationship to the order and the status of the report.
- Internal terminology ticket to author and publish the resulting healthterminologies ValueSet in NCTS [FTR-943](https://jira.aws.tooling/browse/FTR-943)

**Comment by dtr-agency** [comment]
This ValueSet when developed will be bound as required in ServiceRequest.status as part of:
- [Service Request - Order Details for Pathology Report #31](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/31)
- [ServiceRequest - Order Details for Diagnostic Imaging Report #43](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/43)
- [ServiceRequest - Order Details for Other Diagnostic Report #39](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/39)

**Comment by dtr-agency** [comment]
# Analysis of codes in the required value sets
Analysis of possible usage of codes in [RequestStatus](https://www.hl7.org/fhir/valueset-request-status.html) 
| Code | Applicable doc type  | In / Out | Rationale | 
| ------------- | ------------- | ------------- | ------------- | 
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |
| TBD | TBD | TBD | TBD |

**Comment by dtr-agency** [comment]
This issue is scoped specifically to support exchange of diagnostic reports so only the reporting context will be progress.

Suggested outcomes:

1. A new ValueSet for ServiceRequest.status containing the codes: 'active', 'on-hold', 'completed'
2. A new ValueSet for the FHIR-driven CDA containing the codes: 'active', 'suspended', 'completed'
3. Two new ConceptMaps to go between the two ValueSets

**Comment by dtr-agency** [comment]
# ValueSet Design Notes
## 1. A new ValueSet for ServiceRequest.status containing the codes: 'active', 'on-hold', 'completed'
| ValueSet element | Suggested value |
| ------------- | ------------- | 
| title | RequestStatus Reporting | 
| name | RequestStatusReporting |
| canonical url | https://healthterminologies.gov.au/fhir/ValueSet/compositionstatus-document-available-1 |
| version | 1.0.0 |
| description | The CompositionStatus Document Available value set includes values that may be used to represent the status of a document that is available for electronic exchange of health information between healthcare providers, and between healthcare providers and the My Health Record system in Australia. | 
| compose | system: "http://hl7.org/fhir/request-status"; concept: [code: "active"; code: "on-hold"; code: "completed"]  | 

Associated FHIR Terminology Request: [FTR-943](https://jira.aws.tooling/browse/FTR-943)

## 2. A new ValueSet for the FHIR-driven CDA containing the codes: 'active', 'suspended', 'completed'
| ValueSet element | Suggested value |
| ------------- | ------------- | 
| title | v3.ActStatus Request Reporting | 
| name | v3.ActStatusRequestReporting |
| canonical url | https://healthterminologies.gov.au/fhir/ValueSet/tbd-1 |
| version | 1.0.0 |
| description | The v3.ActStatus Request Reporting value set includes values that may be used to represent the status of a request for a service in a reporting context. The values may be used to indicate that results that fulfill in whole or in part this request are available for electronic exchange of health information between healthcare providers, and between healthcare providers and the My Health Record system in Australia. | 
| compose | system: "http://terminology.hl7.org/CodeSystem/v3-ActStatus"; concept: [code: "active"; code: "suspended""; code: "completed"]| 

Associated FHIR Terminology Request: [TBD](TBD)

**Comment by dtr-agency** [comment]
# ConceptMap Design Notes
## 4. Two new ConceptMaps to go between the 1st Composition.status ValueSet and the new ValueSet for ClinicalDocument/ext:completionCode
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | RequestStatus Reporting to v3.ActStatus Request Reporting  | 
| name | requeststatus-reporting-to-v3.actstatus-request-reporting |
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/requeststatus-reporting-to-v3-actstatus-request-reporting-1 |
| version | 1.0.0 |
| description | The RequestStatus Reporting to v3.ActStatus Request Reporting concept map defines relationships from the concepts in the RequestStatus Reporting value set to the concepts in the v3.ActStatus Request Reporting value set. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/v3-actstatus-request-reporting-1 | 
| group | [code: active; target code: active; equivalence: equivalent] [code: on-hold; target code: suspended; equivalence: equivalent] [code: completed; target code: completed; equivalence: equivalent] | 

Associated FHIR Terminology Request: [FTR-TBD](https://jira.aws.tooling/browse/FTR-TBD)

And
| ConceptMap element | Suggested value |
| ------------- | ------------- | 
| title | v3.ActStatus Request Reporting to RequestStatus Reporting | 
| name | nctis-document-available-status-values-to-compositionstatus-document-available |
| canonical url | https://healthterminologies.gov.au/fhir/ConceptMap/v3-actstatus-request-reporting-to-requeststatus-reporting-1 |
| version | 1.0.0 |
| description | The v3.ActStatus Request Reporting to RequestStatus Reporting concept map defines relationships from the concepts in the v3.ActStatus Request Reporting value set to the concepts in the RequestStatus Reporting value set. | 
| sourceCanonical | https://healthterminologies.gov.au/fhir/ValueSet/v3-actstatus-request-reporting-1 | 
| targetCanonical | https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1 | 
| group | [code: active; target code: active; equivalence: equivalent] [code: suspended; target code: on-hold; equivalence: equivalent] [code: completed; target code: completed; equivalence: equivalent] | 

Associated FHIR Terminology Request: [FTR-TBD](https://jira.aws.tooling/browse/FTR-TBD)

**Comment by dtr-agency** [comment]
Designs okayed with product owner, moving to internal review with @robeastwood-agency

**Comment by robeastwood-agency** [comment]
Completed review of the above design; no issues raised.

**Comment by dtr-agency** [comment]
Now for review with Terminology Analyst 01/06.

**Comment by LB-Agency** [comment]
> # ValueSet Design Notes
> ## 1. A new ValueSet for ServiceRequest.status containing the codes: 'active', 'on-hold', 'completed'
> ValueSet element	Suggested value
> title	RequestStatus Reporting
> name	RequestStatusReporting
> canonical url	https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1
> version	1.0.0
> description	The RequestStatus Reporting value set includes values that may be used to represent the status of a request for a service in a reporting context. The values may be used to indicate that results that fulfill in whole or in part this request are available for electronic exchange of health information between healthcare providers, and between healthcare providers and the My Health Record system in Australia.
> compose	system: "http://hl7.org/fhir/request-status"; concept: [code: "active"; code: "on-hold"; code: "completed"]
> Associated FHIR Terminology Request: [FTR-943](https://jira.aws.tooling/browse/FTR-943)
> 
> ## 2. A new ValueSet for the FHIR-driven CDA containing the codes: 'active', 'suspended', 'completed'
> ValueSet element	Suggested value
> title	v3 ActStatus Request Reporting
> name	v3.ActStatusRequestReporting
> canonical url	https://healthterminologies.gov.au/fhir/ValueSet/v3-actstatus-request-reporting-1
> version	1.0.0
> description	The v3 ActStatus Request Reporting value set includes values that may be used to represent the status of a request for a service in a reporting context. The values may be used to indicate that results that fulfill in whole or in part this request are available for electronic exchange of health information between healthcare providers, and between healthcare providers and the My Health Record system in Australia.
> compose	system: "http://terminology.hl7.org/CodeSystem/v3-ActStatus"; concept: [code: "active"; code: "suspended""; code: "completed"]
> Associated FHIR Terminology Request: [FTR-994](https://jira.aws.tooling/browse/FTR-994)

Regarding naming of value set number 2, I can see what's intended by included the underlying code system title and name verbatim, but existing conventions are a little different. 

Firstly, dots are not used in the representation of name with the latest convention being upper camel case with acronyms and initialisms all upper case. I would suggest the inclusion of HL7 to v3 to improve communication of context. 

Secondly, existing content (noting STU3 specific at this stage) uses conventions such as "Immunization Act Status HL7 v3" or "Medication Act Status HL7 v3". There's an opportunity to review this convention but the de facto convention should be noted.

**Comment by dtr-agency** [comment]
@LB-Agency - we've moved on from your comment. This GitHub issue does not have that content.

**Comment by LB-Agency** [comment]
@dtr-agency - moved on to what exactly? What is the scope of this issue now?

**Comment by dtr-agency** [comment]
Terminology Analyst review identified issues with Concept Map canonical url length and use of conventions in name field.

Name field has been removed and will be defined by terminology analyst as part of authoring service. Canonical url trimmed; may need more.

**Comment by dtr-agency** [comment]
Now accepted. Moving to publication schedule.

**Comment by dtr-agency** [comment]
This issue has been shifted to 'complete'; publication of the content in NCTS is pending release of NTS 2.0.

**Comment by dtr-agency** [comment]
To remain open until publication is confirmed.

**Comment by dtr-agency** [comment]
NCTS 2.0 is now live with [RequestStatus Reporting](https://api.healthterminologies.gov.au/integration/R4/fhir/ValueSet/requeststatus-reporting-1). 

The other value set is still to be published; this issue will remain open.

**Comment by dtr-agency** [comment]
Publication complete.
