### ISSUE TITLE
ValueSet - DiagnosticReport.category - pathology diagnostic service

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#61]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The feature
## Description
We need to create a value set for the category element of pathology domain DiagnosticReport profiles to send pathology diagnostic service. The ValueSet should support exchange of pathology reports issued by pathology service providers for the electronic exchange of pathology reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The values are preferred to be drawn from the [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) ValueSet which uses the v2 DIAGNOSTIC SERVICE SECTION ID [v2.0074](http://hl7.org/fhir/R4/v2/0074/index.html) code system.

This ValueSet would be bound to the Pathology domain DiagnosticReport profiles in the forthcoming Diagnostics Report FHIR implementation Guide; it would also be used to indicate diagnostic service categories in profiles in Continuity of Care specifications e.g. Discharge Summary and Event Summary. The ValueSet would also be bound in the corresponding CDA implementation guides.

## Concerns
1. the ValueSet needs to be responsive to the release of new codes for pathology

An extensional defined set would need manual intervention but is there a reasonable means of having a intentional defined set when drawing a subset of codes from [HL7 Version 2 Table 0074](http://hl7.org/fhir/R4/v2/0074/index.html)?

## What it actually enables people to do
Clarifies to implementers requirements for set of codes relevant to pathology. Provision of management of the set of values in a governed manner that is reusable.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.

## Workarounds
A. Leave the binding as-is.
B. Strengthen the binding strength from preferred to extensible or required.

## Additional context
- the ValueSet [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) is preferred in the [AU Base DiagnosticReport](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnosticreport.html) profile we be derive from
- that preferred ValueSet is the set implemented in My Health Record system for CDA R2 documents aka HL7: Diagnostic Service Section ID 2.16.840.1.113883.12.74 in all current specs
- This set is to be consistent with [Australian Pathology Messaging - Localisation of HL7 Version 2.4 4 Observation Reporting](https://confluence.hl7australia.com/display/APM24/4+Observation+Reporting#id-4ObservationReporting-table0074)
- Internal terminology ticket to author and publish the resulting healthterminologies ValueSet in NCTS [FTR-953](https://jira.aws.tooling/browse/FTR-953)

**Comment by dtr-agency** [comment]
This ValueSet when developed will be bound as required in DiagnosticReport.category as part of:
- [Pathology Report with atomic content #21](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/21)
- [My Health Record Pathology Report #23](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/23)

**Comment by dtr-agency** [comment]
# Analysis of codes in the required value set
Analysis of possible usage of codes in [HL7 v2 table 0074 (DIAGNOSTIC SERVICE SECTION ID)](http://hl7.org/fhir/R4/v2/0074/index.html) 
| Code | Display  | In / Out | Rationale | 
| ------------- | ------------- | ------------- | ------------- | 
|AU | Audiology |  TBD | TBD |
|BG | Blood Gases |  TBD | TBD |
BLB | Blood Bank |  TBD | TBD |
CG | Cytogenetics |  TBD | TBD |
CH | Chemistry |  TBD | TBD |
CP | Cytopathology |  TBD | TBD |
CT | CAT Scan |  TBD | TBD |
CTH | Cardiac Catheterization |  TBD | TBD |
CUS | Cardiac Ultrasound |  TBD | TBD |
EC | Electrocardiac (e.g., EKG, EEC, Holter) |  TBD | TBD |
EN | Electroneuro (EEG, EMG,EP,PSG) |  TBD | TBD |
GE | Genetics |  TBD | TBD |
HM | Hematology |  TBD | TBD |
ICU | Bedside ICU Monitoring |  TBD | TBD |
IMM | Immunology |  TBD | TBD |
LAB | Laboratory |  TBD | TBD |
MB | Microbiology |  TBD | TBD |
MCB | Mycobacteriology |  TBD | TBD |
MYC | Mycology |  TBD | TBD |
NMR | Nuclear Magnetic Resonance |  TBD | TBD |
NMS | Nuclear Medicine Scan |  TBD | TBD |
NRS | Nursing Service Measures |  TBD | TBD |
OSL | Outside Lab |  TBD | TBD |
OT | Occupational Therapy |  TBD | TBD |
OTH | Other |  TBD | TBD |
OUS | OB Ultrasound |  TBD | TBD |
PF | Pulmonary Function |  TBD | TBD |
PHR | Pharmacy |  TBD | TBD |
PHY | Physician (Hx. Dx, admission note, etc.) |  TBD | TBD |
PT | Physical Therapy |  TBD | TBD |
RAD | Radiology |  TBD | TBD |
RC | Respiratory Care (therapy) |  TBD | TBD |
RT | Radiation Therapy |  TBD | TBD |
RUS | Radiology Ultrasound |  TBD | TBD |
RX | Radiograph |  TBD | TBD |
SP | Surgical Pathology |  TBD | TBD |
SR | Serology |  TBD | TBD |
TX | Toxicology |  TBD | TBD |
VR | Virology |  TBD | TBD |
VUS | Vascular Ultrasound |  TBD | TBD |
XRC | Cineradiograph| TBD | TBD |

**Comment by dtr-agency** [comment]
@davidmckillop, can you please review the above analysis of codes against the three domains? and could you please provide a comment on whether the inclusion of OTH would be appropriate in the pathology-specific set we are designing?

**Comment by davidmckillop** [comment]
@dtr-agency, yes I would include OTH in the pathology-specific set and I've had agreement with @LB-Agency on this.

**Comment by dtr-agency** [comment]
This issue is scoped specifically to support exchange of pathology reports so only the pathology context work will be progressed.

Suggested outcomes:
1. A new ValueSet for pathology diagnostic service the agreed codes marked as applicable to pathology above.

**Comment by dtr-agency** [comment]
# ValueSet Design Notes
## 1. A new ValueSet for pathology diagnostic service category from  [HL7 v2 table 0074 (DIAGNOSTIC SERVICE SECTION ID)](http://hl7.org/fhir/R4/v2/0074/index.html)
| ValueSet element | Suggested value |
| ------------- | ------------- | 
| title | Pathology Diagnostic Service Category | 
| name | PathologyDiagnosticServiceCategory |
| canonical url | https://healthterminologies.gov.au/fhir/ValueSet/pathology-diagnostic-service-category-1 |
| version | 1.0.0 |
| description | The Pathology Diagnostic Service Category value set includes values that may be used to represent the diagnostic service where a pathology observation was performed to support the electronic exchange of pathology test results between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.| 
| compose | system: "http://hl7.org/fhir/request-status"; concept: TBD | 

Associated FHIR Terminology Request: [FTR-953](https://jira.aws.tooling/browse/FTR-953)

**Comment by dtr-agency** [comment]
Query for Terminology Analyst - the ValueSet needs to be responsive to the release of new codes for pathology.

An extensional defined set would need manual intervention but is there a reasonable means of having a intentional defined set when drawing a subset of codes from HL7 Version 2 Table 0074?

What is suggested for meeting this requirement?

**Comment by dtr-agency** [comment]
Product owner okayed designs; Now for internal review and review with Terminology Analyst 01/06.

**Comment by robeastwood-agency** [comment]
Internal review completed; no issues found.

**Comment by LB-Agency** [comment]
> @dtr-agency, yes I would include OTH in the pathology-specific set and I've had agreement with @LB-Agency on this. OTH allows a provider to use this code in circumstances where the service provider feels the codes in the valueset do not best suit their needs e.g. a specialist lab or a laboratory for a specific purpose e.g. a forensic laboratory. OTH also accommodates new values that are not suited to any of the existing values.
> The code "VR" needs to be included in the pathology valueset.
> All other codes (including VR) listed in the table above are relevant inclusions in the pathology group.
> 
> @davidmckillop I have now edited the table to have VR associated with pathology. Do you have any further comments?
> @dtr-agency - no further issues found. The pathology list is complete.

I see little value in using "extensible" binding over "required" with the inclusion of "OTH" in the set. If there is an expectation a code should be provided from the set, including "OTH" means there is always an applicable value available. Further meaning could then be conveyed through an additional coding element (cardinality max=*) with a value from a different system. Perhaps SNOMED CT-AU descendants of [Pathology service](http://ontoserver.csiro.au/shrimp/?concept=310074003&system=http://snomed.info/sct&versionId=http://snomed.info/sct/32506021000036107/version/20200531). These are the same services bound in AU Base to [HealthcareService.type](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthcareservice-definitions.html#HealthcareService.type).

**Comment by LB-Agency** [comment]
Regarding the responsiveness to new codes being added to HL7 Version 2 Table 0074, the value set definition will be specific to version 2.9. There should be a maintenance review of all value sets binding specific versions of things following the release of a new fhir version.

**Comment by LB-Agency** [comment]
> # ValueSet Design Notes
> ## 1. A new ValueSet for pathology diagnostic service category from [HL7 v2 table 0074 (DIAGNOSTIC SERVICE SECTION ID)](http://hl7.org/fhir/R4/v2/0074/index.html)
> ValueSet element	Suggested value
> title	Pathology Diagnostic Service Category
> name	PathologyDiagnosticServiceCategory
> canonical url	https://healthterminologies.gov.au/fhir/ValueSet/pathology-diagnostic-service-category-1
> version	1.0.0
> description	The Pathology Diagnostic Service Category value set includes values that may be used to indicate the diagnostic service where a pathology observation was performed.
> compose	system: "http://hl7.org/fhir/request-status"; the following codes are required to be included "BG", "BLB", "CG", "CH", "CP", "GE", "HM", "IMM", "LAB", "MB", "MCB", "MYC", "OSL", "OTH", "SP", "SR", "TX", "VR"
> _the codes are listed as a requirement; there is no constraint on the exact means of inclusion when authoring the value set._
> 
> Associated FHIR Terminology Request: [FTR-953](https://jira.aws.tooling/browse/FTR-953)

The current proposed naming (Pathology Diagnostic Service Category) implies that there will only be one value set for all pathology categories and restricts the naming of different future ones. Perhaps the naming could reflect the values in the definition and be more along the lines of "Pathology Diagnostic Service Sections"?

**Comment by dtr-agency** [comment]
@LB-Agency; that name was considered and is not as desired; the peer review and product owner has ended for content.

**Comment by dtr-agency** [comment]
Now accepted. Moving to publication schedule.

**Comment by dtr-agency** [comment]
This issue has been shifted to 'complete'; publication of the content in NCTS is pending release of NTS 2.0.

**Comment by dtr-agency** [comment]
To remain open until publication is confirmed.

**Comment by dtr-agency** [comment]
NCTS 2.0 is now live with [Pathology Diagnostic Service Category](https://api.healthterminologies.gov.au/integration/R4/fhir/ValueSet/pathology-diagnostic-service-category-1). 

ConceptMaps are in the authoring and publication schedule for later this year.
