### ISSUE TITLE
Invariants on references are overly complex - consider generic invariants to simplify

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-r4#63]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
Profiles that contain elements where their datatype is a Reference, also include invariants that seek to improve the quality of those references. Specifically, only allowing the child elements of reference, an identifier or a display. 

Our profiles contain an invariant for each of their affected elements, on their parent element. For profiles with a large number of such elements, the number of the invariants makes it difficult to read the differential table. 

As profile designers, we believe that this is overly complex and we are seeking a better approach.

One approach to simplify the invariants has been suggested to have profiles of the Reference datatype created to write the invariants once, essentially. This has been raised here: #18

Another approach is to investigate the use of generic FHIRPath expressions such as the core specification does for things such as element. That is, to have the equivalent of wherever this type of reference is found, then apply the following rules. As yet, the viability of this approach has not been determined.

## What it actually enables people to do
Easier for developers to understand and build instances against our profiles.

## Mockups 
n/a

## How awesome would it be?
Simplifying these constraints would make our job of profile authors easier but also make it easier for developers to create instances conforming to these profiles.

## Workarounds
None- it is not currently 'broken'

## Additional context
n/a

**Comment by dtr-agency** [comment]
Reference constraints, including their presentation, have been refined during development of ADHA FHIR IG v1.0.0. Where possible generic invariants have been placed.

The approach of using profiles of Reference has not been pursued, see https://github.com/AuDigitalHealth/ci-fhir-r4/issues/18.
