### ISSUE TITLE
Pathology Report example - 2019 Novel Coronavirus PCR (short form)

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#64]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
This example of a "2019 Novel Cornonavirus PCR" report is to present a pathology report with some meta data and an attached pdf.  This report is a representation of a report issued by a diagnostic service provider with key supporting elements of clinical relevance for the electronic exchange of pathology reports between healthcare providers and the My Health Record system infrastructure in Australia.

## What it actually enables people to do
This example will enable developers to view the structure and content of a suitable pathology report with key supporting elements and an attached pdf that is suitable for the electronic exchange of pathology reports between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## How awesome would it be?
Many developers find examples useful especially if one similar to their use case can be found i.e. the more and varied examples the better.

## Workarounds
A developer could always read the specification and Diagnostics implementation guide and develop their own content.

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dbojicic-agency** [comment]
In progress via internal ticket CIFMM-3311.

**Comment by dbojicic-agency** [comment]
The example passed internal review. Rebuilt Diagnostic Report to include the example, see [0bd887f](https://github.com/AuDigitalHealth/ci-fhir-r4/commit/0bd887f6987278e93013f7e208ff2e92049faef4).

**Comment by dtr-agency** [comment]
Note workaround URL in DiagnosticReport for the Pathology Report PDF due to https://github.com/AuDigitalHealth/ci-fhir-r4/issues/74.

**Comment by dtr-agency** [comment]
This example was completed as a bundle (id=559b66ea-abbf-45fb-8627-554817830095) of type collection containing:
- one DiagnosticReport (id=59033ee7-1950-4a04-abb3-6a232d5f62fd) that references
    - ServiceRequest (id=f606666a-23bf-4947-87ba-688824c12c08) that references
         - Patient (id=7e5a8c0a-4e93-4bbb-a369-22572c8a0c3c)
         - PractitionerRole (id=f1d5844f-dd39-457d-867b-f50a00f91731)
    - Patient (id=7e5a8c0a-4e93-4bbb-a369-22572c8a0c3c)
    - PractitionerRole (id=a971cabe-bab5-4e12-b6cb-39f526d17093) that references
            - Practitioner (id=21bf7f1d-f171-45ff-9f6d-3481f48ad468)
            - Organization (id=e0c5fa86-2184-4a5b-8c47-041422643440)
    -  Observation (id=21b82b5b-9acc-49c8-8634-2fdb7b18b283) that references
            - Patient (id=7e5a8c0a-4e93-4bbb-a369-22572c8a0c3c)



DiagnosticReport.text has been used to represent a rendering similar in style to the Agency style sheet.
