### ISSUE TITLE
Pathology Report example - 2019 Novel Coronavirus PCR (atomic)

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#65]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This example of a "2019 Novel Cornonavirus PCR" report is to present a pathology report with atomic data (observation) with and attached pdf. This report is a representation of a report issued by a diagnostic service provider with atomic content (observations with values) and elements of clinical relevance for the electronic exchange of pathology reports between healthcare providers in Australia.

## What it actually enables people to do
This example will enable developers to view the structure and content of a suitable pathology report with atomic content (observation(s) with value(s)) and an attached pdf that is suitable for the electronic exchange of pathology reports between healthcare providers in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## How awesome would it be?
Many developers find examples useful especially if one similar to their use case can be found i.e. the more and varied examples the better.

## Workarounds
A developer could always read the specification and Diagnostics implementation guide and develop their own content.

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dbojicic-agency** [comment]
Started working on a Bundle of type=document' with a Composition resource as the grouper. Need to have a conversation with product owner about details of the story before progressing too far.

**Comment by dbojicic-agency** [comment]
Agreed with the product owner to create a Bundle with the type of 'document', with the Composition resource as the grouper to demonstrate the use case is for a standalone diagnostic report (not MHR). Report is attached to the document as base64 encoded PDF.

**Comment by dbojicic-agency** [comment]
Created example that contains: Composition/c1260f19-f229-4cab-887d-c59d885541c2, Patient/304dd21e-5c79-4a04-88c8-03face00eb78, PractitionerRole/0a0ff7e0-b328-4f5e-aed8-1adb8d1a30fc, Practitioner/839021c8-3d4a-4759-9d70-9d46eb9f5ff5, Organization/e0c5fa86-2184-4a5b-8c47-041422643440,DiagnosticReport/c879220e-b99d-4ac1-9307-8b0036029641, Observation/c074083a-b70a-4bbf-9f82-6ef1a56202d9, Observation/59e2ba97-44b0-45db-8f61-0a1b0e198580, Specimen/81a46e66-3d35-45d4-8f6c-8041d902160d, ServiceRequest/b03d838d-f483-4f92-bf6f-37b1b2d5bebc, PractitionerRole/f1d5844f-dd39-457d-867b-f50a00f91731
Ready for PO walk through.

**Comment by dtr-agency** [comment]
In internal review with @dtr-agency

**Comment by dtr-agency** [comment]
Review issues:

1. The HI Vendor test data patients are not to be re-used in such a way that it is inconsistent with the HI Vendor test data. Bert Gainey cannot be used without their/his? IHI.
The same will be applicable for any HI Vendor test organizations or practitioners - where used they must retain compliance.
Little bits and pieces like the address from one or the IHI from another can be reused elsewhere but we are not to use these HI Vendor Test entities in examples unless they are consistent with the HI Vendor test data.
2. The rendering is in an MHR example - this is a P2P example though since the patient cannot be sent to the MHR so it is not an atomic content that can be sent to the MHR. It would be good for the rendering to show a difference. Please adjust this preferrably to match the PDF.
3. The ServiceRequest.identifier.system is for the Bondi GP center (the NSW example) but the requester is from the Algregster Medical Center - fix the local namespace to be consistent with the PractitionerRole. Likely a HPI-O scoped namespace is necessary as the requesting PracitionerRole has a local id using that namespace.
4. Looking for this example to represent a single individual test; only one Observation no Observation.hasMember content.

**Comment by dbojicic-agency** [comment]
Made following changes:
1. Updated patient in the Bundle to include the missing HI Vendor test data.
2. Changed rendering to match a real-life pathology report; the PDF attachment and the rendering of the example match.
3. Fixed the ServiceRequest.identifier.system to be in the sane HPI-O scoped namespace as the requesting PractitionerRole.identifier.system.
6. Removed second observation; DiagnosticReport is now referencing a single Observation.

**Comment by dtr-agency** [comment]
1. and 4. appear to be missing; think there are some missed commits.

**Comment by dbojicic-agency** [comment]
Yes, stashed changes weren't brought in properly. 
Changes made & available for another review.

**Comment by dbojicic-agency** [comment]
This example was completed as a **Bundle** (id=[b317aa04-131c-49d1-b9bc-48ff94876834](https://github.com/AuDigitalHealth/ci-fhir-r4/blob/master/examples/bundle-b317aa04-131c-49d1-b9bc-48ff94876834.xml)) of type collection containing:
- **DiagnosticReport** (id=c879220e-b99d-4ac1-9307-8b0036029641) that references
    - **ServiceRequest** (id=b03d838d-f483-4f92-bf6f-37b1b2d5bebc)  that references
         - **Patient** (id=304dd21e-5c79-4a04-88c8-03face00eb78)
         - **PractitionerRole** (id=f1d5844f-dd39-457d-867b-f50a00f91731)
    - **Patient** (id=304dd21e-5c79-4a04-88c8-03face00eb78)
    - **Organization** (id=e0c5fa86-2184-4a5b-8c47-041422643440")
    - **PractitionerRole** (id=0a0ff7e0-b328-4f5e-aed8-1adb8d1a30fc) that references
         - **Practitioner** (id=839021c8-3d4a-4759-9d70-9d46eb9f5ff5)
        -  **Organization** (id=e0c5fa86-2184-4a5b-8c47-041422643440)
    -  **Observation** (id=59e2ba97-44b0-45db-8f61-0a1b0e198580) that references
         - **Patient** (id=304dd21e-5c79-4a04-88c8-03face00eb78)
         - **Organization** (id=e0c5fa86-2184-4a5b-8c47-041422643440")
         - **PractitionerRole** (id=0a0ff7e0-b328-4f5e-aed8-1adb8d1a30fc) that references
                - **Practitioner** (id=839021c8-3d4a-4759-9d70-9d46eb9f5ff5)
                 -  **Organization** (id=e0c5fa86-2184-4a5b-8c47-041422643440)
         - **Specimen** (id=81a46e66-3d35-45d4-8f6c-8041d902160d) that references
                 - **Patient** (id=304dd21e-5c79-4a04-88c8-03face00eb78)




   
DiagnosticReport.text has been used to represent a rendering similar in style to the Agency style sheet.
