### ISSUE TITLE
Patient profiles - HL7 AU Base Patient - future extension for birth plurality: add must support in our profiles

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-r4#66]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
There is a feature request on the HL7 AU Base Patient to add an extension to represent a patient's birth plurality (refer https://github.com/hl7au/au-fhir-base/issues/417). Once this extension becomes available in that profile, our derived patient profiles can then make use of this extension. 
This is therefore a request to include a must support on this extension in our patient profiles, once it becomes available. Those profiles are:
- Patient with Mandatory identifier 
- My Health Record Patient

## What it actually enables people to do
This extension allows the recording of the total number of births from one pregnancy - eg 2nd of **4**
## Mockups 
n/a

## How awesome would it be?
A useful addition to the design to facilitate better patient identification. 

## Workarounds
n/a

## Additional context
n/a

**Comment by dtr-agency** [comment]
We need to triage this; its good content for AU Base but we need to assess whether there are requirements for inclusion by default into Agency profiles.

**Comment by RichardTON** [comment]
We will adopt this in R5 via AU Base.
For R4 it can wait until we have a documented requirement for it.
