### ISSUE TITLE
My Health Record Patient :: outstanding features

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#67]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue
## Change description
There are a number of outstanding features for My Health Record Patient profile to be implemented:

1. My Health Record Patient canonical URL to be non-FHIR version specific
2. year of arrival is included
3. Patient.contact and its children to be consistent with advice - advice to date is that contact information is rejected when sent to MHR but BAs do not want this to be prohibited for now, the inclusion of must support flags on these elements is not consistent with this advice
4. generalPractitioner to satisfy requirements - the current content does not satisfy the requirement for a patient to allow inclusion of at most one primary care provider that is a practitioner with included organisational information (aka PractitionerRole)
5. StructureDefinition.description and Patient.short improved in line with Patient with Mandatory Identifier
6. canonical URL change (removing '4.0') in other profiles to be proliferated - affects profiles Base Organization and Base PractitionerRole

In the implementation guides the introductory material is absent; this needs to be resolved in order to provide clarity on the purpose, use, and guidance on implementation for this profile.

Additionally the known issues should be brought into line with the clarity and completeness of other profiles.

## What it actually enables people to do
Basically have a working profile that is more aligned to My Health Record system requirements.

## How awesome would it be?
Fairly - the features are targeted towards high value, low cost improvements in providing a profile that reflects requirements on representing a patient when exchanging health information with the My Health Record system.
The informative improvements provide a better basis for stakeholder engagement, future work and clarity in demonstrating how the overarching usage scenarios in the implementation guide would be served.

## Workarounds
N/A

## Additional context
- Recent informative material added for Patient with Mandatory Identifier as part of https://github.com/AuDigitalHealth/ci-fhir-r4/issues/4 should be taken as the standard for this profile.
- [Use FHIR version independent canonical URLs for Agency profiles #17](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/17)

**Comment by dbojicic-agency** [comment]
Changes to the My Health Record Patient profile now in progress via internal ticket CIFMM-3484.

**Comment by dtr-agency** [comment]
Product owner walkthrough - changes made and now okayed content. In internal review with @SatyaYelisetti

**Comment by dbojicic-agency** [comment]
Internal review with @SatyaYelisetti passed. 
My Health Record Patient profile implementing above features 
profile is now available in master branch as part of the Diagnostic Report IG and the Event Summary IG (via [f159cc7](https://github.com/AuDigitalHealth/ci-fhir-r4/commit/977a75f492f4cd16a38e6af5f3a71f769983cd37)).

Any further issues with the patient profiles will be raised as separate tickets.
