### ISSUE TITLE
Organization with Mandatory Identifier :: outstanding features

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#68]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue
## Change description
There are a number of outstanding features for Organization with Mandatory Identifier profile to be implemented:

1.  canonical URL is non-FHIR version specific
2. StructureDefinition.description and Organization.short improved in line with current language
3. Organization.active matches the decision log Constraints on element active in Agency CI FHIR profiles
4. referenced profiles have corrected canonical URL (removing '4.0')

In the implementation guides the introductory material is largely placeholder; this needs to be resolved in order to provide clarity on the purpose, use, and guidance on implementation for this profile.

Additionally the known issues should be brought into line with the clarity and completeness of other profiles.

## What it actually enables people to do
Basically have a working profile.

## How awesome would it be?
Very - the features are targeted towards keeping this profile functioning.
The informative improvements provide a better basis for stakeholder engagement, future work and clarity in demonstrating how the overarching usage scenarios in the implementation guide would be served.

## Workarounds
N/A

## Additional context
- Recent changes in the style and content to be added in  informative material is demonstrated in recent work for Patient with Mandatory Identifier as part of https://github.com/AuDigitalHealth/ci-fhir-r4/issues/4.
- [Use FHIR version independent canonical URLs for Agency profiles #17](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/17)

**Comment by dtr-agency** [comment]
The following feature changes have been implemented:
- canonical URL is non-FHIR version specific
- StructureDefinition.description and Organization.short improved in line with current language
- Organization.active matches the decision log Constraints on element active in Agency CI FHIR profiles
- referenced profiles have corrected canonical URL (removing '4.0')

Diagnostic Report FHIR IG intro.md has draft introductory material (context, purpose) and implementation guidance that covers at least the general guidance for this profile
Diagnostic Report FHIR IG known issues have been updated

At this time updating Event Summary is out of scope - will occur at a later time.

**Comment by dtr-agency** [comment]
Product owner (@dtr-agency) walkthrough requested minor changes; these have been made and content okayed. Moving to internal review with @vikasmittal-dh.

**Comment by LB-Agency** [comment]
Internal review completed by @vikasmittal-dh

**Comment by LB-Agency** [comment]
Defects in intro.md resolved (profile references and heading size). Review competed @dbojicic-agency.

**Comment by LB-Agency** [comment]
This issue is now closed. Remaining known issues are documented in the profile's known issue table.
