### ISSUE TITLE
Create R4 PractitionerRole profiles for re-use in common scenarios

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#7]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
This story is to create PractitionerRole profiles for re-use in common scenarios in ci-fhir-r4 on BitBucket and to integrate the profile into the currently available R4 FHIR IGs in ci-fhir-r4. 

## What it actually enables people to do
The profiles will define Agency models for the concept of a practitioner roles (a practitioner in a role) in exchange usage scenarios, defining fundamental concepts that form a conforming representation of a patient.

## Mockups 
N/A

## How awesome would it be?
Fundamentally awesome - this is the basis of the Agency concept of a practitioner role in R4 FHIR in clinical data exchange including terminology, identifiers, etc. This contributes to the basic foundation for interoperability, re-use, and optimisation.

## Workarounds
N/A

## Additional context
- [Use FHIR version independent canonical URLs for Agency profiles #17](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/17)

**Comment by dtr-agency** [comment]
PractitionerRole with Mandatory Identifier authored and included in Event Summary FHIR IG & Diagnostic Report FHIR IG: https://github.com/AuDigitalHealth/ci-fhir-r4/commit/c611d2335d6a6c6a027e2f22073d42cbac4c215c

**Comment by dtr-agency** [comment]
Base PractitionerRole required to support Patient.generalPractitioner in My Health Record Patient and Patient with Mandatory Identifier.

**Comment by dbojicic-agency** [comment]
In review with @dbojicic-agency.
