### ISSUE TITLE
PractitionerRole with Mandatory Identifier :: outstanding features

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#70]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue
## Change description
There are a number of outstanding features for PractitionerRole with Mandatory Identifier profile to be implemented:

1.  canonical URL is non-FHIR version specific
2. StructureDefinition.description and PractitionerRole.short improved in line with current language
3. referenced profiles have corrected canonical URL (removing '4.0')

In the implementation guides the introductory material is largely placeholder; this needs to be resolved in order to provide clarity on the purpose, use, and guidance on implementation for this profile.

Additionally the known issues should be brought into line with the clarity and completeness of other profiles.

## What it actually enables people to do
Basically have a working profile.

## How awesome would it be?
Very - the features are targeted towards keeping this profile functioning.
The informative improvements provide a better basis for stakeholder engagement, future work and clarity in demonstrating how the overarching usage scenarios in the implementation guide would be served.

## Workarounds
N/A

## Additional context
- Recent changes in the style and content to be added in  informative material is demonstrated in recent work for Patient with Mandatory Identifier as part of https://github.com/AuDigitalHealth/ci-fhir-r4/issues/4.
- [Use FHIR version independent canonical URLs for Agency profiles #17](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/17)

**Comment by RichardTON** [comment]
Passed internal review; rebuilt Diagnostic Report to complete the profile and introductory content. See  d1cb761

**Comment by RichardTON** [comment]
Built on master 
Diagnostic Report IG - first draft of R4 Base PractitionerRole
Diagnostic Report IG and Event Summary IG - PractitionerRole with Mandatory Identifier :: phase 2
see 7367a82
