### ISSUE TITLE
Valueset - DiagnosticReport.category - Imaging diagnostic service

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#75]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
We need to create a value set for the category element of diagnostic imaging domain DiagnosticReport profiles to send diagnostic imaging diagnostic service. The ValueSet should support exchange of diagnostic imaging reports issued by diagnostic imaging service providers for the electronic exchange of diagnostic imaging reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

The values are preferred to be drawn from the [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) ValueSet which uses the [v2.0074](http://hl7.org/fhir/R4/v2/0074/index.html) v2.0074 code system.

However, it is known that some diagnostic imaging providers in Australia use the [v2.0074](http://hl7.org/fhir/R4/v2/0259/index.html) v2.0259 code system, but the contents of this code system have been deprecated by HL7.  

The other option is the [DICOM Acquisition Modality](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html)

This ValueSet would be bound to the Diagnostic Imaging domain DiagnosticReport profiles in the forthcoming Diagnostics Report FHIR implementation Guide; it would also be used to indicate diagnostic service categories in profiles in Continuity of Care specifications e.g. Discharge Summary and Event Summary. The ValueSet would also be bound in the corresponding CDA implementation guides.

## Concerns
1. the ValueSet needs to be responsive to the release of new codes for diagnostic imaging

An extensional defined set would need manual intervention but is there a reasonable means of having a intentional defined set when drawing a subset of codes from [HL7 Version 2 Table 0074](http://hl7.org/fhir/R4/v2/0074/index.html)?

## What it actually enables people to do
Clarifies to implementers requirements for set of codes relevant to diagnostic imaging. Provision of management of the set of values in a governed manner that is reusable.

## How awesome would it be?
Pretty awesome - clarity of requirements is always desired, and management by terminology binding is the preferred means in CI Agency profiles of specifying more than one allowed values for an element.

## Workarounds
A. Leave the binding as-is.
B. Strengthen the binding strength from preferred to extensible or required.

## Additional context
- the ValueSet [Diagnostic Service Section Codes](http://hl7.org/fhir/R4/valueset-diagnostic-service-sections.html) is preferred in the [AU Base DiagnosticReport](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnosticreport.html) profile we be derive from
- that preferred ValueSet is the set implemented in My Health Record system for CDA R2 documents aka HL7: Diagnostic Service Section ID 2.16.840.1.113883.12.74 in all current specs
- This set is to be consistent with [Australian Pathology Messaging - Localisation of HL7 Version 2.4 4 Observation Reporting](https://confluence.hl7australia.com/display/APM24/4+Observation+Reporting#id-4ObservationReporting-table0074)
- Internal terminology ticket to author and publish the resulting healthterminologies ValueSet in NCTS [FTR-954](https://jira.aws.tooling/browse/FTR-954)

**Comment by dtr-agency** [comment]
Relates to and overlaps with #55

**Comment by davidmckillop** [comment]
Content in this ticket is duplicated in #55.  This ticket (#75) is closed.
