### ISSUE TITLE
Other Diagnostic Report example - Macular Optical Coherence Tomography (OCT) (atomic)

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#82]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This example of a "Macular Optical Coherence Tomography (OCT)"  is to present a specialist and other diagnostic report with some meta data and an attached pdf. This report is a representation of a report issued by a diagnostic service provider with key supporting elements of clinical relevance for the electronic exchange of a specialist and other diagnostic reports between healthcare providers and the My Health Record system infrastructure in Australia.

## What it actually enables people to do
This example will enable developers to view the structure and content of a suitable specialist and other diagnostic report with key supporting elements and an attached pdf that is suitable for the electronic exchange of a specialist and other diagnostic reports between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## How awesome would it be?
Many developers find examples useful especially if one similar to their use case can be found i.e. the more and varied examples the better.

## Workarounds
A developer could always read the specification and Diagnostics implementation guide and develop their own content.

**Comment by dbojicic-agency** [comment]
Closed in [41a931d](https://github.com/AuDigitalHealth/ci-fhir-r4/commit/41a931d4568a3bcac512ccf7b471249df04f6865).
