### ISSUE TITLE
FixedPattern conflict in DiagnosticReport.category; Observation.category; ServiceRequest.category

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-r4#87]
# Prerequisites

- [X] I have verified the problem exists in the available content
- [X] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
The use of FixedPattern is conflicting with the intended design - we want to fix a domain category, e.g. imaging, and encourage the sending of a second finer grained category, but current profile forces all instances of category to match the fixed pattern.... which is the right behaviour of fixed pattern but the wrong behaviour for our profiles. For:
* DiagnosticReport.category
* Observation.category
* ServiceRequest.category

## What I expected to happen
A resource without one instance of category that has the desired value should fail with error.
A resource with only one instance of category with the desired value of category should pass.
A resource with one or more instances of category with a different code to the desired value in addition to one instance of category with the desired value of category should pass.

## Workarounds
Could just remove entirely.

## QA.html excerpt
An instance of DiagnosticReport we want to pass inside a Bundle (see below for code) is failing.
```
<DiagnosticReport>
...
        <category>
          <coding>
            <system value="http://terminology.hl7.org/CodeSystem/v2-0074"/>
            <code value="LAB"/>
          </coding>
        </category>
        <category>
          <coding>
            <system value="http://terminology.hl7.org/CodeSystem/v2-0074"/>
            <code value="MB"/>
          </coding>
        </category>
...
<DiagnosticReport>
```
Bundle/559b66ea-abbf-45fb-8627-554817830095: Bundle.entry[0].resource.category[1] (l372/c27) | error | Expected CodeableConcept pattern not found for system: http://terminology.hl7.org/CodeSystem/v2-0074 code: LAB display: null - Issues: [ValidationMessage[level=ERROR,type=VALUE,location=Bundle.entry[0].resource.category[1].coding.code,message=Value is "MB" but must be "LAB"]]
-- | -- | --

## Additional context
Not an issue for Other Diagnostics profiles that do not fix a category.

**Comment by dtr-agency** [comment]
### Removed patternCodeableConcept

- Removed patternCodeableConcept from DiagnosticReport.category in 
   - DiagnosticReport (Atomic Diagnostic Imaging Report)
   - DiagnosticReport (Atomic Pathology Report)
   - DiagnosticReport (My Health Record Diagnostic Imaging Report)
   - DiagnosticReport (My Health Record Pathology Report)

- Removed patternCodeableConcept from ServiceRequest.category in 
   - ServiceRequest (Order Details for Diagnostic Imaging Report)
   - ServiceRequest (Order Details for Pathology Report)

- Removed patternCodeableConcept from Observation.category in 
   - Observation (Atomic Imaging Observation)
   - Observation (Atomic Pathology Observation)
   - Observation (Simple Imaging Observation)
   - Observation (Simple Pathology Observation)

**Comment by dtr-agency** [comment]
### Added invariant to ensure one category shall be ...
Added invariant that One category shall be 'imaging' 'http://terminology.hl7.org/CodeSystem/observation-category' - FHIRPath only enforcing category.coding.code value and not system in this draft (system may not be needed an extensible value set is expected to be bound here.).
Added to:
- DiagnosticReport (Atomic Diagnostic Imaging Report)
- DiagnosticReport (My Health Record Diagnostic Imaging Report)
- Observation (Atomic Imaging Observation)
- Observation (Simple Imaging Observation)

Added invariant that One category shall be 'imaging' 'http://terminology.hl7.org/CodeSystem/observation-category' - FHIRPath only enforcing category.coding.code value and not system in this draft (system may not be needed an extensible value set is expected to be bound here.).
Added to:
- DiagnosticReport (Atomic Pathology Report)
- DiagnosticReport (My Health Record Pathology Report)

Added invariant that One category shall be 'laboratory' 'http://terminology.hl7.org/CodeSystem/observation-category' - FHIRPath only enforcing category.coding.code value and not system in this draft .
Added to:
- Observation (Atomic Pathology Observation)
- Observation (Simple Pathology Observation)

Added invariant that One category shall be 'LAB' 'http://terminology.hl7.org/CodeSystem/v2-0074' - FHIRPath only enforcing category.coding.code value and not system in this draft (system may not be needed as category is bound as extensible).
Added to:
- ServiceRequest (Order Details for Diagnostic Imaging Report)

Added invariant that One category shall be '108252007' 'http://snomed.info/sct' - FHIRPath only enforcing category.coding.code value and not system in this draft (system may not be needed as the SNOMED codes are fairly unique).
Added to:
- ServiceRequest (Order Details for Pathology Report)

**Comment by dtr-agency** [comment]
Removed category (pattern) known issue now this is fixed in the profiles for:
- DiagnosticReport (Atomic Diagnostic Imaging Report)
- DiagnosticReport (Atomic Pathology Report)
- DiagnosticReport (My Health Record Diagnostic Imaging Report)
- DiagnosticReport (My Health Record Pathology Report)
- ServiceRequest (Order Details for Diagnostic Imaging Report)
- ServiceRequest (Order Details for Pathology Report)
- Observation (Atomic Pathology Observation)
- Observation (Simple Imaging Observation)
- Observation (Simple Pathology Observation)

NOTE: Observation (Atomic Imaging Observation) known issues have not been touched as the phase 2 work for this profile including updating the known issues is in progress and thus this profile did not have this issue documented yet.

**Comment by dtr-agency** [comment]
Ready for joint product owner review @davidmckillop and internal reviewer @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
In review with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
Confirmed all changes made as described. Suggest including system value for the expression to fully match invariant description. This be machine processable and probably easier for novice readers to understand.

**Comment by dtr-agency** [comment]
Added system value; please review.

**Comment by dbojicic-agency** [comment]
Confirmed changes, all new invariants include system and code values now.

**Comment by dtr-agency** [comment]
Merged, regenerated, pushed to GitHub.
