### ISSUE TITLE
Other Diagnostic Report example - Echocardiography Report (atomic)

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#94]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This example of a "Echocardiography Report" is to present a specialist and other diagnostic report  with atomic data (observation) with and attached pdf.  This report is a representation of a report issued by a diagnostic service provider with atomic content (observations with values) and elements of clinical relevance for the electronic exchange of other diagnostic reports between healthcare providers in Australia.

## What it actually enables people to do
This example will enable developers to view the structure and content of a suitable other diagnostic report with atomic content (observation(s) with value(s)) and an attached pdf that is suitable for the electronic exchange of other diagnostic reports between healthcare providers in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## How awesome would it be?
Many developers find examples useful especially if one similar to their use case can be found i.e. the more and varied examples the better.

## Workarounds
A developer could always read the specification and Diagnostics implementation guide and develop their own content.

**Comment by dtr-agency** [comment]
Had initial discussion with product owner on direction of story. Some edits made to description to match current path. This will be progressed in parallel with the MHR scenario #93 

The MHR and Atomic will be two flavours of the exact same report. So for elements included in both the same exact value is expected - there will be three main differences:
- MHR uses Bundle type=document with a Composotion as the grouper
- Atomic uses Bundle type=collection with a DiagnosticReport as the grouper
- Same patient, author, etc. (same values for the clinical/business elements that are present in both) but the elements included will differ (some added or removed between scenarios); and of course the technical elements will have different values e.g. unique ids as the ids are for the resources as entries into the Bundle not the business identifier or unique meta.lastUpdated etc.

**Comment by dtr-agency** [comment]
Pre-existing that will be used: Patient (mhr-zhang-wei) and Organization (nsw-hospital) and PractitionerRole (nsw-gp)

Created the following to be added to the examples folder to be used in this (and other examples if useful)
- PractitionerRole cardiologist (46d552b7-88a9-427b-9d62-8b0727de91f9) Practitioner (d68312c9-b122-4fe5-8e3c-f550bd989f4b)
- PractitionerRole sonographer (04ac8978-bc60-4492-aa07-f62568ebe5c6) Practitioner (e6de10ad-8dba-4250-8399-311da99e8c30)
- PractitionerRole oncologist (cb084861-dd87-48ff-b645-5cb620a00e8e) for requester

And the actual clinical stuff to go: 1 * Bundle, 1 * DiagnosticReport, 1 * ServiceRequest, and so many observations

**Comment by dtr-agency** [comment]
Created Atomic example using Bundle type=collection with a DiagnosticReport as the grouper. 

Example is an attempt to:
* get as close as possible to the sample PDF available: G:\NEHTA Projects\CI\FHIR\FHIR IG\Diagnostics\Other-Daignostics\Cardiology\Echocardiography-report.pdf. 
* be aligned with the MHR flavour
* See internal design page as linked above (https://confluence.digitalhealth.gov.au/pages/viewpage.action?pageId=134680448).

Bundle contains:
* a DiagnosticReport (code is Echocardiography SNOMED) 
* a primary study Observation (code is Echocardiography SNOMED) that hasMember 8 grouping Observations that each have observations with value via hasMember (38 individual result Observations in total)
   - example attempts to include as much coded granularity as possible and thus may diverge from a atomic set of content 
* a ServiceRequset (code is Echocardiography SNOMED)
* an ImagingStudy that provides an endpoint to get access to the study images - an Endpoint
* 2 PractitionerRole performers with corresponding 2 Practitioners
* 1 PractitionerRole requester
* 1 Organization (NSW Hospital)
* 1 Patient (Mr Zhang Wei but the P2P form)

DiagnosticReport.text demonstrates a rendering as close to the sample PDF as possible and contains some additional narrative.

**Comment by dtr-agency** [comment]
Ready for product owner walkthrough.

**Comment by dtr-agency** [comment]
Product owner okayed content in principle - will perform internal review at same time as independent reviewer. Waiting on merge of atomic other diag fixes to put out for review.

**Comment by dtr-agency** [comment]
Sent for internal review with @davidmckillop (Product owner) and @RichardTON.

**Comment by dtr-agency** [comment]
Quick review completed and fixes confirmed.

**Comment by dtr-agency** [comment]
Merged, rebuilt, pushed to GitHub.
