### ISSUE TITLE
PractitionerRole.location requires use case investigation with respect to cardinality

### ISSUE THREAD

**Issue by LB-Agency** [AuDigitalHealth/ci-fhir-r4#95]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description

There has been little investigation into the cardinality requirements for PractitionerRole.location in the current profiles, Base PractitionerRole and PractitionerRole with Mandatory Identifier.

Investigation should be done and use cases defined to determine if the max. cardinality of location should remain as many or be constrained to 1. Multiple locations may lead to ambiguity on what roles and specialties a practitioner is performing for an organisation at a specific location and what healthcare services are being supported at a specific location.

## What it actually enables people to do

Enables practitioner's to unambiguously represent the roles, specialities and services provided for an organisation at a specific location. 

## Mockups 
None

## How awesome would it be?

Clearly awesome. Unambiguous representation is paramount. 

## Workarounds

None

## Additional context
None

**Comment by dtr-agency** [comment]
May 2022 QA Preview - http://build.fhir.org/ig/AuDigitalHealth/ci-fhir-r4/branches/2022May/package.tgz
Release 1.0.0 is limited to the FHIR R4 conformance artefacts that define the controls on data persistence for the following record types: Australian Immunisation Register, Australian Organ Donor Register, PBS/RPBS Claim Information, MBS/DVA Claim Information.

The FHIR R4 conformance artefacts are a set of StructureDefinitions that define the FHIR structures required, the data element definitions, and their associated rules of usage including the use of extensions and terminology. These conformance artefacts will be published in an Agency FHIR NPM package for use with FHIR and FHIR-aware tools. The FHIR package contains the validation form (JSON + SCH) of the conformance artefacts for direct use in validation operations and example resource instances that demonstrate use cases and conformance requirements.

While these artefacts and their package have been developed in conjunction with this Agency FHR implementation guide – publication and release of the implementation guide is not in scope. The implementation guide is provided to assist readers and users in understanding the Agency FHIR NPM package. See http://build.fhir.org/ig/AuDigitalHealth/ci-fhir-r4/branches/2022May/index.html

---------------------------------------------------------

Development and internal design architecture review is complete, internal unit testing is underway via [AN-3](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/AN-3), Clinical Informatics peer review is underway via [AN-5](https://jira.digitalhealth.gov.au/browse/AN-5), [AN-6](https://jira.digitalhealth.gov.au/browse/AN-6), [AN-7](https://jira.digitalhealth.gov.au/browse/AN-7), and [AN-8](https://jira.digitalhealth.gov.au/browse/AN-8).

**Comment by dtr-agency** [comment]
Testing on AU Base PractitionerRole complete with no changes required.
