### ISSUE TITLE
BodyStructure tighten terminology binding on location and locationQualifier 

### ISSUE THREAD

**Issue by dbojicic-agency** [AuDigitalHealth/ci-fhir-r4#98]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
BodyStructure.location
Tighten the binding strength of https://healthterminologies.gov.au/fhir/ValueSet/body-site-1 to be required

BodyStructure.locationQualifier - 
There is a new value set forthcoming, see https://github.com/hl7au/au-fhir-base/issues/575. When this is available the binding strength to locationQualifier should be at extensible. In addition a minimum value set of SNOMED CT 
to enforce that the code must be SNOMED CT though possibly fixing the system value may be sufficient.

## What it actually enables people to do
tbd

## Mockups 
None

## How awesome would it be?
tbd 

## Workarounds
None

## Additional context
insert legacy content

**Comment by dtr-agency** [comment]
Australian Digital Health Agency Core BodyStructure in development; will include this fix.
